#!/usr/bin/env python
"""
Real Randomized Benchmarking replication for arXiv:1801.06121
Hashagen, Flammia, Gross, Wallman (2018)

Single-qubit implementation. Compare standard Clifford RB vs Real Clifford RB
under a real-diagonal noise channel (only X/Z Pauli errors, no Y).

Real Clifford group C(1) = <Z, H>  (paper eq. 17)
  - Subgroup of full 1-qubit Clifford group (24 elements).
  - Enumerating <Z, H> generates the 2x2 real orthogonal matrices from
    {+/-1} entries with a 1/sqrt(2) factor -> order 8 group (contains
    I, Z, H, HZ, ZH, HZH, ZHZ, and identity variants; equivalent to
    dihedral D4 as a real matrix group).

Real-diagonal noise: E(rho) = (1-p) rho + (p/2) X rho X + (p/2) Z rho Z
  (no Y term). This is a "real" Pauli channel; consistent with paper's
  focus on real errors in the real orthogonal commutant.

Standard 1-qubit Clifford RB expected model:
  F(m) = A + B * f^m  (single decay when noise is depolarizing-like)

Real 1-qubit RB expected model (from paper eq. 43 restricted to real rho):
  F(m) = A + B * b^m  (single decay in the "b" channel)

For real-diagonal noise on a real initial state |0><0|, both fits
should extract *related* decay parameters. Paper's central claim: the
real Clifford group is an orthogonal 2-design and can efficiently
extract the "b" decay rate (real part of the error) using ONLY 8
group elements per gate slot instead of 24.

Efficiency comparison: with the same total shot budget, real RB should
give competitive (or better) statistical estimates for the real-error
component b, since the group is 3x smaller and the twirl over it is
still an exact 2-design over the orthogonal group.
"""

import json
import time
from pathlib import Path

import numpy as np
from scipy.optimize import curve_fit
from qiskit import QuantumCircuit
from qiskit.quantum_info import Operator, Clifford, random_clifford
from qiskit_aer import AerSimulator
from qiskit_aer.noise import NoiseModel, pauli_error

RNG = np.random.default_rng(20260703)

# ---------- Real Clifford group C(1) = <Z, H> ------------------------

def _enumerate_real_clifford_1q():
    """Enumerate the subgroup of U(2) generated by {Z, H}. Returns list of
    (unique) 2x2 unitary matrices."""
    Z = np.array([[1, 0], [0, -1]], dtype=complex)
    H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
    gens = [Z, H]
    seen = {}
    frontier = [np.eye(2, dtype=complex)]

    def key(M):
        # canonicalize up to global sign (paper's C(1) as orthogonal matrices,
        # elements of O(2) form the "physical" 8-element group).
        Mr = np.round(M, 8) + 0.0
        # normalize global phase: pick element with largest |M[i,j]| first-nonzero
        flat = Mr.flatten()
        for x in flat:
            if abs(x) > 1e-6:
                phase = x / abs(x)
                break
        else:
            phase = 1.0
        Mn = Mr / phase
        return tuple(np.round(Mn, 6).flatten())

    while frontier:
        nxt = []
        for M in frontier:
            k = key(M)
            if k in seen:
                continue
            seen[k] = M
            for g in gens:
                nxt.append(g @ M)
                nxt.append(M @ g)
        frontier = nxt
    return list(seen.values())


REAL_CLIFFORD_1Q = _enumerate_real_clifford_1q()
print(f"[init] |Real Clifford group C(1)| = {len(REAL_CLIFFORD_1Q)} (paper: should be 8 as orthogonal matrices up to global phase)")


# ---------- Full 1-qubit Clifford group (24 elements) ---------------

def _enumerate_full_clifford_1q():
    """Enumerate the 24 single-qubit Cliffords using S, H generators."""
    S = np.array([[1, 0], [0, 1j]], dtype=complex)
    H = np.array([[1, 1], [1, -1]], dtype=complex) / np.sqrt(2)
    gens = [S, H]
    seen = {}
    frontier = [np.eye(2, dtype=complex)]

    def key(M):
        Mr = np.round(M, 8) + 0.0
        flat = Mr.flatten()
        for x in flat:
            if abs(x) > 1e-6:
                phase = x / abs(x)
                break
        else:
            phase = 1.0
        Mn = Mr / phase
        return tuple(np.round(Mn, 6).flatten())

    while frontier:
        nxt = []
        for M in frontier:
            k = key(M)
            if k in seen:
                continue
            seen[k] = M
            for g in gens:
                nxt.append(g @ M)
                nxt.append(M @ g)
        frontier = nxt
    return list(seen.values())


FULL_CLIFFORD_1Q = _enumerate_full_clifford_1q()
print(f"[init] |Full Clifford group C(1) complex| = {len(FULL_CLIFFORD_1Q)} (should be 24)")


# ---------- Circuit builders ----------------------------------------

def matrix_to_gate_circuit(U, num_qubits=1):
    qc = QuantumCircuit(num_qubits)
    qc.unitary(U, list(range(num_qubits)), label='C')
    return qc


def build_rb_sequence(group, m):
    """Draw m random elements from `group`, compute inverting gate C_{m+1},
    build the circuit, and return it."""
    idxs = RNG.integers(0, len(group), size=m)
    U = np.eye(2, dtype=complex)
    for i in idxs:
        U = group[i] @ U
    U_inv = U.conj().T  # inverse (unitary)
    qc = QuantumCircuit(1, 1)
    for i in idxs:
        qc.unitary(group[i], [0])
    qc.unitary(U_inv, [0])
    qc.measure(0, 0)
    return qc


# ---------- Noise model ---------------------------------------------

def real_diagonal_noise(p):
    """Real-diagonal Pauli channel: p/2 X, p/2 Z, 1-p I. No Y term."""
    err = pauli_error([('X', p / 2), ('Z', p / 2), ('I', 1 - p)])
    noise = NoiseModel()
    # Apply after every unitary and measurement gate
    noise.add_all_qubit_quantum_error(err, ['unitary'])
    return noise


# ---------- Experiment runner ---------------------------------------

def run_rb(group, group_label, ms, num_sequences, shots, noise):
    sim = AerSimulator(noise_model=noise)
    survival = np.zeros(len(ms))
    survival_std = np.zeros(len(ms))
    print(f"[run] {group_label}: |G|={len(group)}, ms={list(ms)}, seq/len={num_sequences}, shots={shots}")
    t0 = time.time()
    for i, m in enumerate(ms):
        p_seqs = []
        for s in range(num_sequences):
            qc = build_rb_sequence(group, m)
            result = sim.run(qc, shots=shots).result()
            counts = result.get_counts()
            p_survive = counts.get('0', 0) / shots
            p_seqs.append(p_survive)
        survival[i] = float(np.mean(p_seqs))
        survival_std[i] = float(np.std(p_seqs) / np.sqrt(num_sequences))
        print(f"  m={m:3d}: F={survival[i]:.4f} +/- {survival_std[i]:.4f}  (n_seq={num_sequences})")
    dt = time.time() - t0
    print(f"[run] {group_label} done in {dt:.1f}s")
    return survival, survival_std


def rb_decay(m, A, B, f):
    return A + B * (f ** m)


def fit_rb(ms, F, sigma):
    # weighted nonlinear fit
    try:
        popt, pcov = curve_fit(
            rb_decay, ms, F,
            p0=[0.5, 0.5, 0.99],
            bounds=([0, 0, 0], [1, 1, 1]),
            sigma=sigma, absolute_sigma=True, maxfev=20000
        )
        perr = np.sqrt(np.diag(pcov))
        A, B, f = popt
        A_e, B_e, f_e = perr
    except Exception as e:
        print(f"[fit] curve_fit failed: {e}; falling back to unweighted")
        popt, pcov = curve_fit(rb_decay, ms, F, p0=[0.5, 0.5, 0.99],
                                bounds=([0, 0, 0], [1, 1, 1]), maxfev=20000)
        perr = np.sqrt(np.diag(pcov))
        A, B, f = popt
        A_e, B_e, f_e = perr
    # 1-qubit: standard EPC r = (d-1)/d * (1-f) = (1-f)/2
    d = 2
    r = (d - 1) / d * (1 - f)
    r_err = (d - 1) / d * f_e
    return dict(A=A, B=B, f=f, A_err=A_e, B_err=B_e, f_err=f_e, r=r, r_err=r_err)


# ---------- Main experiment -----------------------------------------

def main():
    outdir = Path(__file__).resolve().parent.parent / 'report' / 'evidence'
    outdir.mkdir(parents=True, exist_ok=True)

    # Injected error rate
    p_inject = 0.02  # 2% real-diagonal Pauli error per unitary
    # Expected f_std under standard RB with a 50/50 X+Z Pauli channel of total
    # weight p: process infidelity = p, so f_std = 1 - 2r = 1 - 2*(p/(1)) ... actually
    # for a Pauli channel with total error weight p, average gate infidelity r = p/2
    # (for depolarizing-equivalent single-qubit) -> f = 1 - 2r = 1 - p. But this is
    # X+Z only, no Y -> only 2 non-trivial Paulis, so this is a "partial" depolarizing
    # channel; the effective b and f from twirling should differ.
    ms_std = [1, 5, 10, 20, 40, 80, 150]
    ms_real = [1, 5, 10, 20, 40, 80, 150]
    num_seq_std = 30
    num_seq_real = 30
    shots = 1024

    noise = real_diagonal_noise(p_inject)

    print(f"\n=== Injecting real-diagonal noise p={p_inject} (X/2, Z/2, no Y) ===\n")

    # Standard 1-qubit Clifford RB
    F_std, s_std = run_rb(FULL_CLIFFORD_1Q, "Std Clifford (24 elts)",
                          ms_std, num_seq_std, shots, noise)
    fit_std = fit_rb(np.array(ms_std), F_std, s_std)
    print(f"[fit] Std:  f={fit_std['f']:.4f} +/- {fit_std['f_err']:.4f}, "
          f"r={fit_std['r']:.4f} +/- {fit_std['r_err']:.4f}")

    # Real 1-qubit Clifford RB
    F_real, s_real = run_rb(REAL_CLIFFORD_1Q, "Real Clifford (8 elts)",
                            ms_real, num_seq_real, shots, noise)
    fit_real = fit_rb(np.array(ms_real), F_real, s_real)
    print(f"[fit] Real: b={fit_real['f']:.4f} +/- {fit_real['f_err']:.4f}, "
          f"r_R={fit_real['r']:.4f} +/- {fit_real['r_err']:.4f}")

    # Efficiency: what happens if real-RB uses fewer sequences due to smaller group?
    # Reduce num_seq_real to |real|/|std| * num_seq_std = 8/24 * 30 = 10
    num_seq_real_reduced = max(4, int(round(num_seq_std * len(REAL_CLIFFORD_1Q) / len(FULL_CLIFFORD_1Q))))
    print(f"\n=== EFFICIENCY TEST: real RB with only {num_seq_real_reduced} sequences/length ===")
    F_real_eff, s_real_eff = run_rb(REAL_CLIFFORD_1Q, "Real Clifford (reduced seqs)",
                                    ms_real, num_seq_real_reduced, shots, noise)
    fit_real_eff = fit_rb(np.array(ms_real), F_real_eff, s_real_eff)
    print(f"[fit] Real (reduced): b={fit_real_eff['f']:.4f} +/- {fit_real_eff['f_err']:.4f}, "
          f"r_R={fit_real_eff['r']:.4f} +/- {fit_real_eff['r_err']:.4f}")

    result = dict(
        paper='arXiv:1801.06121',
        title='Real Randomized Benchmarking',
        p_inject=p_inject,
        ms_std=list(map(int, ms_std)),
        ms_real=list(map(int, ms_real)),
        num_seq_std=num_seq_std,
        num_seq_real=num_seq_real,
        num_seq_real_reduced=num_seq_real_reduced,
        shots=shots,
        real_group_size=len(REAL_CLIFFORD_1Q),
        full_group_size=len(FULL_CLIFFORD_1Q),
        standard_rb=dict(
            survival=list(map(float, F_std)),
            survival_sem=list(map(float, s_std)),
            fit=fit_std,
        ),
        real_rb=dict(
            survival=list(map(float, F_real)),
            survival_sem=list(map(float, s_real)),
            fit=fit_real,
        ),
        real_rb_reduced=dict(
            survival=list(map(float, F_real_eff)),
            survival_sem=list(map(float, s_real_eff)),
            fit=fit_real_eff,
        ),
    )

    with open(outdir / 'results.json', 'w') as fp:
        json.dump(result, fp, indent=2, default=lambda x: float(x) if isinstance(x, np.floating) else str(x))
    print(f"\n[save] {outdir / 'results.json'}")

    # Print concise comparison
    print("\n" + "=" * 70)
    print("COMPARISON: standard vs real Clifford RB, injected p = ", p_inject)
    print("=" * 70)
    print(f"{'protocol':<30} {'|G|':>6} {'#seq':>6} {'decay f/b':>14} {'r':>14}")
    print(f"{'Standard Clifford RB':<30} {24:>6} {num_seq_std:>6} "
          f"{fit_std['f']:.4f}±{fit_std['f_err']:.3f}    "
          f"{fit_std['r']:.4f}±{fit_std['r_err']:.3f}")
    print(f"{'Real Clifford RB':<30} {8:>6} {num_seq_real:>6} "
          f"{fit_real['f']:.4f}±{fit_real['f_err']:.3f}    "
          f"{fit_real['r']:.4f}±{fit_real['r_err']:.3f}")
    print(f"{'Real Clifford RB (reduced)':<30} {8:>6} {num_seq_real_reduced:>6} "
          f"{fit_real_eff['f']:.4f}±{fit_real_eff['f_err']:.3f}    "
          f"{fit_real_eff['r']:.4f}±{fit_real_eff['r_err']:.3f}")

    return result


if __name__ == '__main__':
    main()
