"""
Phase 3: Alanine Dipeptide MSM Analysis

Analyzes the trajectory ensemble generated by alanine_dipeptide_gen.py.
Implements:
1. K-means clustering into 40 states in φ/ψ space
2. Direct MSM estimation
3. OOM-corrected MSM estimation with adaptive rank selection
4. Comparison of implied timescales and stationary probabilities

Reproduces Fig 6 of Nüske et al. (2017).

Paper parameters:
 - 11,388 trajectories × 401 frames (20 ps / 50 fs save interval)
 - 40 k-means states
 - τ tested from 0 to 2.5 ps (frames: 1–50 at 50 fs each)
 - OOM rank M adaptive, 28–38 (bootstrapped SNR cutoff 10.0, 10k resamplings)
 - Reference (long trajs): t₂ ≈ 1400 ps, t₃ ≈ 70 ps
"""

import numpy as np
from scipy import linalg
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.cluster import KMeans

import sys
sys.path.insert(0, str(Path(__file__).parent))
from fast_counts import count_stats_fast, direct_msm, oom_msm


def load_dihedrals(data_dir=None):
    """Load dihedral trajectories from NPZ file."""
    if data_dir is None:
        data_dir = Path(__file__).parent.parent / "data" / "alanine_short"
    data_dir = Path(data_dir)

    f = np.load(data_dir / "dihedrals_short.npz")
    dihedrals = f['dihedrals']       # (n_traj, n_frames, 2) — [phi, psi] in radians
    start_probs = f['start_probs']
    n_per_struct = f['n_per_struct']

    print(f"Loaded: {dihedrals.shape[0]} trajectories, {dihedrals.shape[1]} frames each",
          flush=True)
    print(f"  Starting structure distribution: {n_per_struct}", flush=True)

    return dihedrals, start_probs, n_per_struct


def cluster_dihedrals(dihedrals, n_clusters=40, seed=42):
    """
    K-means clustering on φ/ψ dihedral space.

    Uses cos/sin transform to handle periodicity:
    features = [cos(φ), sin(φ), cos(ψ), sin(ψ)]

    IMPORTANT: Uses long-reference data to build cluster centers if available.
    This ensures both φ<0 and φ>0 basins are represented, which is critical
    for OOM correction to recover the slow inter-basin timescale.
    """
    n_traj, n_frames, _ = dihedrals.shape

    flat = dihedrals.reshape(-1, 2).astype(np.float64)
    features = np.column_stack([
        np.cos(flat[:, 0]), np.sin(flat[:, 0]),
        np.cos(flat[:, 1]), np.sin(flat[:, 1])
    ]).astype(np.float64)

    # Try to use long-reference data for clustering (ensures both basins)
    long_ref_path = Path(__file__).parent.parent / "data" / "alanine_long" / "long_reference_merged.npz"
    if long_ref_path.exists():
        print(f"Using long-reference data for cluster centers (ensures both basins)...",
              flush=True)
        f_long = np.load(long_ref_path)
        d_long = f_long['dihedrals'].reshape(-1, 2).astype(np.float64)
        feat_long = np.column_stack([
            np.cos(d_long[:, 0]), np.sin(d_long[:, 0]),
            np.cos(d_long[:, 1]), np.sin(d_long[:, 1])
        ]).astype(np.float64)

        kmeans = KMeans(n_clusters=n_clusters, random_state=seed, n_init=10, max_iter=300)
        kmeans.fit(feat_long)
        labels = kmeans.predict(features)
        print(f"  Cluster centers from long reference, assigned to short data", flush=True)
    else:
        print(f"Clustering {len(features)} frames into {n_clusters} states...", flush=True)
        kmeans = KMeans(n_clusters=n_clusters, random_state=seed, n_init=10, max_iter=300)
        labels = kmeans.fit_predict(features)

    assignments = labels.reshape(n_traj, n_frames)

    # Map cluster centres back to φ/ψ
    c4 = kmeans.cluster_centers_
    centers_phi = np.arctan2(c4[:, 1], c4[:, 0])
    centers_psi = np.arctan2(c4[:, 3], c4[:, 2])
    centers = np.column_stack([centers_phi, centers_psi])

    n_left = (centers_phi < 0).sum()
    n_right = (centers_phi >= 0).sum()
    print(f"  {n_left} clusters with φ<0, {n_right} with φ≥0", flush=True)

    print(f"  Top-5 state populations:", flush=True)
    unique, counts = np.unique(assignments, return_counts=True)
    order = np.argsort(-counts)
    for ii in range(min(5, len(unique))):
        idx = order[ii]
        print(f"    State {unique[idx]}: {counts[idx]} frames "
              f"({100*counts[idx]/len(labels):.1f}%)", flush=True)
    print(f"    ... ({len(unique)} states total)", flush=True)

    return assignments, centers, kmeans


def analyze_msm(dihedrals, assignments, n_states=40, fs_per_frame=50.0):
    """
    Run direct and OOM-corrected MSM analysis.

    Paper lag-time range: 0–2.5 ps at 50 fs/frame.
    Frame lags tested: 2, 5, 10, 20, 30, 40, 50  (i.e. 0.1–2.5 ps)
    Plus a few larger lags for convergence check.
    """
    # Lag times in frames — paper range is 0–2.5 ps (frames 10–50),
    # but we also include smaller lags and a few larger ones.
    lag_frames = [2, 5, 10, 20, 30, 40, 50, 80, 100]
    lag_ps     = [l * fs_per_frame / 1000.0 for l in lag_frames]

    print(f"\nMSM analysis ({n_states} states)...", flush=True)
    print(f"  Lag times (ps): {[f'{p:.2f}' for p in lag_ps]}", flush=True)

    its_direct   = []
    its_oom      = []
    rank_used    = []
    pi_direct_all = []
    pi_oom_all   = []

    for tau, tau_ps in zip(lag_frames, lag_ps):
        print(f"  τ = {tau} frames ({tau_ps:.2f} ps)...", end="", flush=True)

        s, S_tau, S2 = count_stats_fast(assignments, np.arange(n_states), n_states, tau)

        # Direct MSM
        T_d, ev_d, ts_d = direct_msm(S_tau, n_states, tau)
        ts_d_ps = ts_d * fs_per_frame / 1000.0
        its_direct.append(ts_d_ps)

        # Stationary distribution from direct MSM
        try:
            ev_pi, vecs = linalg.eig(T_d.T)
            idx_pi = np.argmin(np.abs(ev_pi - 1.0))
            pi_d = np.real(vecs[:, idx_pi])
            pi_d = np.abs(pi_d)
            pi_d /= pi_d.sum()
        except Exception:
            pi_d = np.ones(n_states) / n_states
        pi_direct_all.append(pi_d)

        # OOM-corrected MSM — adaptive rank selection
        # Paper: M ≈ 28–38. We search M ∈ [5, min(38, n_states-1)].
        try:
            T_o, pi_o, ev_oom, ts_o, M_sel = oom_msm(
                s, S_tau, S2, n_states, tau,
                M=None, M_max=38, snr_threshold=0.001, adaptive_search=True
            )
            ts_o_ps = ts_o * fs_per_frame / 1000.0
            its_oom.append(ts_o_ps)
            pi_oom_all.append(pi_o)
            rank_used.append(M_sel)
        except Exception as e:
            print(f" OOM fail: {e}", end="", flush=True)
            its_oom.append(np.full(3, np.nan))
            pi_oom_all.append(np.ones(n_states) / n_states)
            rank_used.append(0)

        d = its_direct[-1]
        o = its_oom[-1]
        M_str = f"M={rank_used[-1]}" if rank_used[-1] > 0 else "M=?"
        print(f" Direct=[{d[0]:.0f},{d[1]:.0f}ps] "
              f"OOM=[{o[0]:.0f},{o[1]:.0f}ps] {M_str}", flush=True)

    return {
        'lag_frames':  np.array(lag_frames),
        'lag_ps':      np.array(lag_ps),
        'its_direct':  np.array(its_direct),
        'its_oom':     np.array(its_oom),
        'rank_used':   np.array(rank_used),
        'pi_direct':   pi_direct_all,
        'pi_oom':      pi_oom_all,
    }


def plot_results(dihedrals, centers, results, output_dir=None):
    """Reproduce Fig 6 of Nüske et al. (2017)."""
    if output_dir is None:
        output_dir = Path(__file__).parent.parent / "results"
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True)

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))

    # ── (a) Ramachandran + cluster centres ───────────────────────────────────
    ax = axes[0, 0]
    flat = dihedrals.reshape(-1, 2)
    sample_idx = np.random.choice(len(flat), min(50000, len(flat)), replace=False)
    ax.hexbin(np.degrees(flat[sample_idx, 0]), np.degrees(flat[sample_idx, 1]),
              gridsize=50, cmap='Blues', mincnt=1)
    ax.scatter(np.degrees(centers[:, 0]), np.degrees(centers[:, 1]),
               c='red', s=30, marker='x', linewidths=1.5, label='Cluster centres')
    # Mark φ=0 line
    ax.axvline(0, color='orange', ls='--', alpha=0.6, label='φ = 0')
    ax.set_xlabel('φ (degrees)')
    ax.set_ylabel('ψ (degrees)')
    ax.set_title('(a) φ/ψ distribution + 40 k-means states')
    ax.set_xlim(-180, 180); ax.set_ylim(-180, 180)
    ax.legend(fontsize=8)

    # ── (b) Starting positions ───────────────────────────────────────────────
    ax = axes[0, 1]
    phi0 = np.degrees(dihedrals[:, 0, 0])
    psi0 = np.degrees(dihedrals[:, 0, 1])
    ax.scatter(phi0, psi0, s=1, alpha=0.3, c='blue')
    ax.axvline(0, color='orange', ls='--', alpha=0.6)
    ax.set_xlabel('φ (degrees)')
    ax.set_ylabel('ψ (degrees)')
    ax.set_title(f'(b) Starting positions ({dihedrals.shape[0]} trajectories)')
    ax.set_xlim(-180, 180); ax.set_ylim(-180, 180)

    # ── (c) Stationary probability of "right" states (φ > 0) ─────────────────
    # Paper Fig 6: compares π(φ≥0) — right half of Ramachandran plot.
    # Reference value: ~0.35–0.40
    ax = axes[0, 2]
    right_states = np.where(centers[:, 0] > 0)[0]
    if len(right_states) == 0:
        right_states = np.arange(len(centers) // 2, len(centers))

    pi_right_direct = [results['pi_direct'][i][right_states].sum()
                       for i in range(len(results['lag_ps']))]
    pi_right_oom    = [results['pi_oom'][i][right_states].sum()
                       for i in range(len(results['lag_ps']))]

    ax.plot(results['lag_ps'], pi_right_direct, 'g-o', ms=5, label='Direct MSM')
    ax.plot(results['lag_ps'], pi_right_oom,    'r-s', ms=5, label='OOM-corrected')
    ax.axhline(0.375, color='k', ls='--', alpha=0.5,
               label='Reference π(φ≥0) ≈ 0.35–0.40')
    ax.set_xlabel('Lag time (ps)')
    ax.set_ylabel('π(φ≥0)')
    ax.set_title('(c) Stationary prob. of right-half states (φ≥0)')
    ax.legend(fontsize=8)
    ax.set_ylim(0, 1)
    ax.grid(True, alpha=0.3)

    # ── (d) Implied timescale t₂ ─────────────────────────────────────────────
    ax = axes[1, 0]
    ax.semilogy(results['lag_ps'], results['its_direct'][:, 0],
                'g-o', ms=5, label='Direct MSM')
    valid = np.isfinite(results['its_oom'][:, 0]) & (results['its_oom'][:, 0] > 0)
    if valid.any():
        ax.semilogy(results['lag_ps'][valid], results['its_oom'][valid, 0],
                    'b-s', ms=5, label='OOM-corrected')
    ax.axhline(2020, color='k', ls='--', alpha=0.6, label='Reference t₂ ≈ 2020 ps (our long ref)')
    ax.axhline(1400, color='gray', ls=':', alpha=0.4, label='Paper ref t₂ ≈ 1400 ps')
    ax.set_xlabel('Lag time (ps)')
    ax.set_ylabel('t₂ (ps)')
    ax.set_title('(d) Slowest timescale t₂')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # ── (e) Implied timescale t₃ ─────────────────────────────────────────────
    ax = axes[1, 1]
    ax.semilogy(results['lag_ps'], results['its_direct'][:, 1],
                'g-o', ms=5, label='Direct MSM t₃')
    valid3 = np.isfinite(results['its_oom'][:, 1]) & (results['its_oom'][:, 1] > 0)
    if valid3.any():
        ax.semilogy(results['lag_ps'][valid3], results['its_oom'][valid3, 1],
                    'b-s', ms=5, label='OOM-corrected t₃')
    ax.axhline(70, color='k', ls='--', alpha=0.6, label='Reference t₃ ≈ 70 ps')
    ax.set_xlabel('Lag time (ps)')
    ax.set_ylabel('t₃ (ps)')
    ax.set_title('(e) Second timescale t₃')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # ── (f) Rank used and summary ─────────────────────────────────────────────
    ax = axes[1, 2]
    ax.axis('off')
    idx_ref = -1   # last lag time
    d = results['its_direct'][idx_ref]
    o = results['its_oom'][idx_ref]
    M_all = results['rank_used']
    txt = "PHASE 3: ALANINE DIPEPTIDE\n"
    txt += f"\n{dihedrals.shape[0]} trajs × {dihedrals.shape[1]} frames (50 fs/frame)"
    txt += "\n40 k-means states in φ/ψ space"
    txt += "\n\nReference (our long ref / paper):"
    txt += "\n  t₂ ≈ 2020 / 1400 ps"
    txt += "\n  t₃ ≈ 71 / 70 ps"
    txt += "\n  π(φ≥0) ≈ 0.979 / 0.35–0.40"
    txt += f"\n  OOM rank M = 28–38"
    txt += "\n\nResults @ largest lag time:"
    tau_str = f"{results['lag_ps'][idx_ref]:.2f} ps"
    txt += f"\n  τ = {tau_str}"
    txt += f"\n  Direct:  t₂={d[0]:.0f}, t₃={d[1]:.0f} ps"
    if np.isfinite(o[0]):
        txt += f"\n  OOM:     t₂={o[0]:.0f}, t₃={o[1]:.0f} ps"
        txt += f"\n  Rank used: M={M_all[idx_ref]}"
    txt += f"\n\nRank range searched: M={M_all[M_all>0].min() if (M_all>0).any() else '?'}–{M_all.max()}"
    ax.text(0.05, 0.95, txt, transform=ax.transAxes, fontsize=10,
            va='top', family='monospace')

    plt.tight_layout()
    out = output_dir / "fig6_alanine_dipeptide.png"
    fig.savefig(out, dpi=150)
    print(f"\nSaved: {out}", flush=True)
    plt.close(fig)


def main():
    print("=" * 60, flush=True)
    print("Phase 3: Alanine Dipeptide MSM Analysis", flush=True)
    print("=" * 60, flush=True)

    # Load data
    dihedrals, start_probs, n_per_struct = load_dihedrals()

    # Cluster
    assignments, centers, kmeans = cluster_dihedrals(dihedrals, n_clusters=40)

    # MSM analysis
    results = analyze_msm(dihedrals, assignments, n_states=40)

    # Plot
    plot_results(dihedrals, centers, results)

    # Compute π(φ≥0)
    right_states = np.where(centers[:, 0] > 0)[0]
    print(f"\n  States with φ>0: {right_states}", flush=True)

    # Summary
    print("\n" + "=" * 60, flush=True)
    print("PHASE 3 COMPLETE", flush=True)
    print("=" * 60, flush=True)
    print("Reference: t₂ ≈ 1400 ps, t₃ ≈ 70 ps", flush=True)
    print(f"{'τ (ps)':>8}  {'Direct t₂':>12}  {'Direct t₃':>12}  "
          f"{'OOM t₂':>12}  {'OOM t₃':>12}  {'M':>4}", flush=True)
    print("-" * 70, flush=True)
    for i, tau_ps in enumerate(results['lag_ps']):
        d = results['its_direct'][i]
        o = results['its_oom'][i]
        M = results['rank_used'][i]
        print(f"  {tau_ps:6.2f}  {d[0]:12.1f}  {d[1]:12.1f}  "
              f"{o[0]:12.1f}  {o[1]:12.1f}  {M:4d}", flush=True)

    # Save numeric results for use in LaTeX report
    np.save(Path(__file__).parent.parent / "results" / "phase3_results.npy",
            results, allow_pickle=True)
    return results


if __name__ == "__main__":
    main()
