"""Build a .mmd-style substitute for the true Nougat parse using pymupdf.
See extraction/README.md for the provenance disclaimer.
"""
import pymupdf
from pathlib import Path

PDF = Path(__file__).parent.parent / "work" / "paper.pdf"
OUT = Path(__file__).parent / "nougat.mmd"

doc = pymupdf.open(str(PDF))
lines: list[str] = []
lines.append("<!-- NOUGAT SUBSTITUTE - see extraction/README.md for provenance -->")
lines.append("<!-- Generated by pymupdf %s; Nougat model NOT run in this environment -->" % pymupdf.__version__)
lines.append("")

for page_num, page in enumerate(doc, 1):
    lines.append(f"\n\n<!-- page {page_num} -->\n")
    text = page.get_text("text")
    # Trivial cleanup: strip page numbers that appear alone on their own line
    for raw in text.split("\n"):
        s = raw.rstrip()
        if s.strip().isdigit() and len(s.strip()) <= 3:
            # likely a page number
            continue
        lines.append(s)

OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {doc.page_count} pages)")
