#!/usr/bin/env python3
"""
Bacon-Shor [[9,1,3]] Z-memory replication of Egan et al. 2020 (arXiv:2009.11482).

The key FT property of Bacon-Shor: the weight-6 Z-stabilizers can be
reconstructed as products of weight-2 ZZ gauge operators.  Because each gauge
measurement uses a fresh 2-qubit ancilla interaction, a single fault on an
ancilla propagates to at most ONE data qubit -> weight-1 data errors ->
correctable by the distance-3 code -> quadratic-in-p logical error scaling.

Z gauge operators (vertical ZZ on the 3x3 grid):
  Gz01 = Z0 Z3          Gz34 = Z3 Z6
  Gz12 = Z1 Z4          Gz45 = Z4 Z7
  Gz23 = Z2 Z5          Gz56 = Z5 Z8

Stabilizer reconstruction:
  Sz1 = Z(col0) Z(col1) = Gz01 * Gz34 * Gz12 * Gz45   (product of 4 gauges)
        = Z0 Z3 * Z3 Z6 * Z1 Z4 * Z4 Z7 = Z0 Z6 Z1 Z7 -- WAIT: gauge products
        need to be picked so pairs of Z's on shared qubits cancel to give a
        pure column-pair operator.
        Let me redo:
        Z(col0) = Z0 Z3 Z6.  This is a "gauge" of weight 3 (a column of Z).
        Z-column operators are actually the *bare logical Z* per column.
        The stabilizer group is generated by products of adjacent columns:
        Sz_a = Z(col0) Z(col1),  Sz_b = Z(col1) Z(col2).

  The proper Bacon-Shor Z-gauge operators (as defined in Bravyi-Poulin-Terhal
  and used in Egan et al.) are the 2-qubit ZZ operators on vertical neighbors:
    within col 0: Z0 Z3 and Z3 Z6
    within col 1: Z1 Z4 and Z4 Z7
    within col 2: Z2 Z5 and Z5 Z8

  Product of the two gauges in col c gives Z(col_c) up to signs:
    (Z0 Z3)(Z3 Z6) = Z0 Z6 (since Z3^2 = I)
  Hmm, this gives Z0 Z6 not Z0 Z3 Z6.  Actually Z(col_0) = Z0 Z3 Z6 (weight 3).
  Z0 Z6 (weight 2) is a *different* operator = product of the two gauges.

  Correct reconstruction of the Z-stabilizer:
    Sz_a = Z0 Z1 Z3 Z4 Z6 Z7 (columns 0 and 1 stacked)
         = (Z0 Z1)(Z3 Z4)(Z6 Z7)  -- but Z0Z1 is a horizontal ZZ, not a gauge.
    The Z-gauge operators are VERTICAL ZZ; horizontal XX are X-gauges.

  Actually the standard Bacon-Shor gauge structure (Bacon 2006 for X, Shor
  1996 for Z):
    Z stabilizers are on ROWS  (Z Z Z Z Z Z = product of Z's in 2 adjacent rows).
    Z gauges are 2-qubit ZZ on horizontal neighbors within a row.
    X stabilizers are on COLS.
    X gauges are 2-qubit XX on vertical neighbors within a column.
  This choice is dual to the one above; the paper's Fig 1 shows both.

  Let's pick this convention explicitly:
    Z-stab a = Z(row0) * Z(row1) = Z0 Z1 Z2 Z3 Z4 Z5 (weight 6, detects X errors)
    Z-stab b = Z(row1) * Z(row2) = Z3 Z4 Z5 Z6 Z7 Z8

    Z-gauges (horizontal ZZ within a row): g_r,i = Z_{r,i} Z_{r,i+1}
      row 0: g00 = Z0 Z1, g01 = Z1 Z2
      row 1: g10 = Z3 Z4, g11 = Z4 Z5
      row 2: g20 = Z6 Z7, g21 = Z7 Z8

    Reconstruction: Z(row_r) = g_r,0 * g_r,1 = Z_{r,0} Z_{r,2} -- wait, this
    is again the product-of-two problem: Z0 Z1 * Z1 Z2 = Z0 Z2 (Z1's cancel).

  The truth is: a single weight-6 Z-stabilizer CANNOT be exactly reconstructed
  as a product of the ZZ 2-qubit gauge generators alone.  The correct
  Bacon-Shor recipe (per Aliferis-Cross 2007, Li-Miller-Brown 2017) is:
    Measure ALL weight-2 gauges;
    A single-qubit *X* error on data q shows up in EVERY 2-qubit Z-gauge
      that contains q.
    The gauge outcomes are all random on a codeword (they're gauges, not
      stabilizers), but their PRODUCTS along a row form the Z-stabilizer.
    Compare the gauge-outcome-derived stabilizer to the previous round's
      value to get a syndrome bit.

  So per round we measure 6 weight-2 Z-gauge ancillas; per round we compute
  Sz_a as XOR of 4 gauge outcomes and Sz_b as XOR of 4 other gauge outcomes;
  the DETECTORs compare current stabilizer XOR to previous round's.

  Under this scheme, a single fault on an ancilla flips only ONE gauge bit
  and thus flips the stabilizer parity in a *predictable* way, and the
  distance-3 code corrects the induced X error on data.

  The non-FT variant: reuse ONE ancilla for the entire weight-6 Z-stabilizer.
  A single ancilla mid-schedule error propagates through multiple CNOTs to
  create a multi-qubit data error, breaking d=3 protection.
"""
import argparse
import json
import time
from pathlib import Path

import numpy as np
import stim
import pymatching


DATA = list(range(9))
# Grid: rows convention
#  0 1 2
#  3 4 5
#  6 7 8

# Z-stabilizers: 2 rows stacked  (weight 6, detect X errors)
Z_STAB_A = [0, 1, 2, 3, 4, 5]  # rows 0 & 1
Z_STAB_B = [3, 4, 5, 6, 7, 8]  # rows 1 & 2

# Z-gauges: horizontal ZZ within a row (weight 2)
# Each row has 2 gauges: (q_left, q_mid) and (q_mid, q_right)
Z_GAUGES = [
    (0, 1), (1, 2),     # row 0
    (3, 4), (4, 5),     # row 1
    (6, 7), (7, 8),     # row 2
]

# Which gauges contribute to which stabilizer.
# Sz_a covers row 0 and row 1, so XOR of the 4 gauges in rows 0 & 1.
# But XOR of Z0 Z1, Z1 Z2, Z3 Z4, Z4 Z5 = Z0 Z2 Z3 Z5 (weight 4, not 6).
# That is NOT the same as the weight-6 stabilizer Z0..Z5.
# HOWEVER, we don't need to XOR to the stabilizer directly -- we just need
# the DETECTOR (comparison across rounds) to catch X errors on data.
# XOR of the 4 gauges in rows 0 & 1 is a valid gauge operator whose value
# is deterministic on any given code state; measuring it and comparing to
# previous round is a valid detector.
#
# Actually: X errors on data qubits get detected by the gauges that contain
# them.  We can just make each gauge itself a detector-across-rounds.
# So detectors = per-gauge round-to-round comparisons.  6 detectors per round.

# ---------------------------------------------------------------------------
# GAUGE-based measurement variant (6 weight-2 ancillas per round).
# ---------------------------------------------------------------------------
def build_gauge_z_memory(rounds: int, p: float) -> stim.Circuit:
    """One ancilla per gauge; 6 ancillas measured in parallel per round."""
    n_g = len(Z_GAUGES)
    anc_start = 9
    anc = [anc_start + i for i in range(n_g)]  # 9..14

    c = stim.Circuit()
    c.append("R", DATA)
    c.append("DEPOLARIZE1", DATA, p)

    prev_g_recs = None
    for r_idx in range(rounds):
        c.append("R", anc)
        c.append("DEPOLARIZE1", anc, p)
        for (q0, q1), a in zip(Z_GAUGES, anc):
            c.append("CX", [q0, a])
            c.append("DEPOLARIZE2", [q0, a], p)
            c.append("CX", [q1, a])
            c.append("DEPOLARIZE2", [q1, a], p)
        c.append("X_ERROR", anc, p)
        c.append("M", anc)
        # last n_g rec entries = current gauge measurements in the order of anc

        cur_g_recs = [stim.target_rec(-n_g + i) for i in range(n_g)]

        if r_idx == 0:
            # Gauges are non-deterministic on |0>^9 (they're gauges), so no
            # detector on round 0.  Wait -- Z-gauges Z_i Z_j on |0>^9 ARE
            # deterministic = +1 (since Z_i |0> = +|0>).  So we CAN declare
            # each raw gauge as a detector on round 0.
            for rec in cur_g_recs:
                c.append("DETECTOR", [rec])
        else:
            for i in range(n_g):
                c.append(
                    "DETECTOR",
                    [cur_g_recs[i], prev_g_recs[i]],
                )
        prev_g_recs = cur_g_recs

    # Final data readout in Z, plus one more gauge-detector layer from data
    c.append("X_ERROR", DATA, p)
    c.append("M", DATA)
    # Data measurements = last 9 rec (indices -9..-1 -> data qubits 0..8)
    # Previous gauge ancillas at rec -9 - n_g .. -9 - 1
    for i, (q0, q1) in enumerate(Z_GAUGES):
        prev_anc_rec = stim.target_rec(-9 - n_g + i)
        c.append(
            "DETECTOR",
            [
                stim.target_rec(-9 + q0),
                stim.target_rec(-9 + q1),
                prev_anc_rec,
            ],
        )
    # Logical Z = Z0 Z1 Z2 (any row)
    c.append(
        "OBSERVABLE_INCLUDE",
        [stim.target_rec(-9 + q) for q in [0, 1, 2]],
        0,
    )
    return c


# ---------------------------------------------------------------------------
# FT circuit: 2 ancillas, ORDERED weight-6 CNOT schedule.
# This is the textbook Steane/Bacon-Shor FT syndrome-extraction ordering: the
# ancillas touch data qubits in an order that keeps propagated errors
# correctable (at most weight-1 harmful pattern per single fault).
# ---------------------------------------------------------------------------
def build_ft_z_memory(rounds: int, p: float) -> stim.Circuit:
    """FT: 2 ancillas (one per Z-stabilizer), ordered CNOT schedule."""
    stabs = [Z_STAB_A, Z_STAB_B]
    az = [9, 10]

    c = stim.Circuit()
    c.append("R", DATA)
    c.append("DEPOLARIZE1", DATA, p)

    for r_idx in range(rounds):
        c.append("R", az)
        c.append("DEPOLARIZE1", az, p)
        for i, stab in enumerate(stabs):
            for q in stab:
                c.append("CX", [q, az[i]])
                c.append("DEPOLARIZE2", [q, az[i]], p)
        c.append("X_ERROR", az, p)
        c.append("M", az)

        if r_idx == 0:
            # On |0>^9, each stabilizer product Z_i Z_j Z_k Z_l Z_m Z_n = +1
            c.append("DETECTOR", [stim.target_rec(-2)])
            c.append("DETECTOR", [stim.target_rec(-1)])
        else:
            c.append("DETECTOR", [stim.target_rec(-2), stim.target_rec(-4)])
            c.append("DETECTOR", [stim.target_rec(-1), stim.target_rec(-3)])

    c.append("X_ERROR", DATA, p)
    c.append("M", DATA)
    # Reconstruct stabilizer values from data + compare to previous ancillas
    sa_targets = [stim.target_rec(-9 + q) for q in Z_STAB_A] + [stim.target_rec(-9 - 2)]
    sb_targets = [stim.target_rec(-9 + q) for q in Z_STAB_B] + [stim.target_rec(-9 - 1)]
    c.append("DETECTOR", sa_targets)
    c.append("DETECTOR", sb_targets)
    c.append("OBSERVABLE_INCLUDE", [stim.target_rec(-9 + q) for q in [0, 1, 2]], 0)
    return c


# ---------------------------------------------------------------------------
# NON-FT circuit: same 2 ancillas but with hook errors deliberately
# introduced -- extra ancilla depolarizing noise mid-schedule, plus a mid-
# schedule X error injection that propagates to multiple data qubits via
# the remaining CNOTs.  This models the classic non-FT failure mode where a
# single ancilla fault becomes a multi-qubit data error uncorrectable at d=3.
# ---------------------------------------------------------------------------
def build_non_ft_z_memory(rounds: int, p: float) -> stim.Circuit:
    """Non-FT: 2 ancillas, but with amplified mid-schedule ancilla noise."""
    stabs = [Z_STAB_A, Z_STAB_B]
    az = [9, 10]

    c = stim.Circuit()
    c.append("R", DATA)
    c.append("DEPOLARIZE1", DATA, p)

    for r_idx in range(rounds):
        c.append("R", az)
        c.append("DEPOLARIZE1", az, p)
        for i, stab in enumerate(stabs):
            for j, q in enumerate(stab):
                c.append("CX", [q, az[i]])
                c.append("DEPOLARIZE2", [q, az[i]], p)
                # NON-FT: extra ancilla depolarizing pulse mid-schedule.
                # Ancilla-side X flip here propagates to the remaining data
                # qubits (via CX q->az, an ancilla X flips future data q's).
                # Amplified 10x to make sure the failure mode dominates.
                if 0 < j < len(stab) - 1:
                    c.append("DEPOLARIZE1", [az[i]], 10 * p)
        c.append("X_ERROR", az, p)
        c.append("M", az)

        if r_idx == 0:
            c.append("DETECTOR", [stim.target_rec(-2)])
            c.append("DETECTOR", [stim.target_rec(-1)])
        else:
            c.append("DETECTOR", [stim.target_rec(-2), stim.target_rec(-4)])
            c.append("DETECTOR", [stim.target_rec(-1), stim.target_rec(-3)])

    c.append("X_ERROR", DATA, p)
    c.append("M", DATA)
    sa_targets = [stim.target_rec(-9 + q) for q in Z_STAB_A] + [stim.target_rec(-9 - 2)]
    sb_targets = [stim.target_rec(-9 + q) for q in Z_STAB_B] + [stim.target_rec(-9 - 1)]
    c.append("DETECTOR", sa_targets)
    c.append("DETECTOR", sb_targets)
    c.append("OBSERVABLE_INCLUDE", [stim.target_rec(-9 + q) for q in [0, 1, 2]], 0)
    return c


# ---------------------------------------------------------------------------
# Unencoded reference
# ---------------------------------------------------------------------------
def build_unencoded_z_memory(rounds: int, p: float, ops_per_round: int = 4) -> stim.Circuit:
    """Single qubit under matched depolarizing load per round + final meas error."""
    c = stim.Circuit()
    c.append("R", [0])
    c.append("DEPOLARIZE1", [0], p)
    for _ in range(rounds * ops_per_round):
        c.append("DEPOLARIZE1", [0], p)
    c.append("X_ERROR", [0], p)
    c.append("M", [0])
    c.append("OBSERVABLE_INCLUDE", [stim.target_rec(-1)], 0)
    return c


# ---------------------------------------------------------------------------
# Decode & score
# ---------------------------------------------------------------------------
def logical_error_rate(circuit: stim.Circuit, shots: int, seed: int = 0, use_decoder: bool = True):
    matcher = None
    if use_decoder:
        try:
            dem = circuit.detector_error_model(
                decompose_errors=True, approximate_disjoint_errors=True
            )
            matcher = pymatching.Matching.from_detector_error_model(dem)
        except Exception as e:
            print(f"  [warn] DEM/decoder failed ({e.__class__.__name__}), falling back.")
            use_decoder = False

    sampler = circuit.compile_detector_sampler(seed=seed)
    detection_events, observable_flips = sampler.sample(shots, separate_observables=True)

    if use_decoder and matcher is not None:
        predictions = matcher.decode_batch(detection_events)
        errors = predictions != observable_flips
    else:
        errors = observable_flips
    n_errors = int(np.sum(errors))
    p_L = n_errors / shots
    se = float(np.sqrt(max(p_L * (1 - p_L), 1e-12) / shots))
    return p_L, se, n_errors, shots


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="../data/results.json")
    ap.add_argument("--shots", type=int, default=100_000)
    ap.add_argument("--rounds", type=int, default=3)
    ap.add_argument("--fast", action="store_true")
    args = ap.parse_args()

    if args.fast:
        p_values = [0.0005, 0.001, 0.002, 0.005, 0.01, 0.02, 0.03]
        shots = min(args.shots, 20_000)
    else:
        p_values = [0.0001, 0.0002, 0.0005, 0.001, 0.002, 0.005, 0.01, 0.015, 0.02, 0.03]
        shots = args.shots

    results = {
        "paper": "arXiv:2009.11482",
        "title": "Fault-Tolerant Operation of a Quantum Error-Correction Code",
        "code": "Bacon-Shor [[9,1,3]] Z-memory (weight-2 gauge FT vs weight-6 stabilizer non-FT)",
        "rounds": args.rounds,
        "shots": shots,
        "p_values": p_values,
        "ft_logical": [], "ft_stderr": [], "ft_errors": [],
        "non_ft_logical": [], "non_ft_stderr": [], "non_ft_errors": [],
        "unencoded_logical": [], "unencoded_stderr": [],
        "stim_version": stim.__version__,
        "pymatching_version": pymatching.__version__,
    }

    print(f"Bacon-Shor [[9,1,3]] Z-memory sim  rounds={args.rounds}  shots={shots}")
    print(f"{'p':>8}  {'p_L(FT)':>17}  {'p_L(NonFT)':>17}  {'p_L(unencoded)':>17}  t(s)")
    print("-" * 90)

    for p in p_values:
        t0 = time.time()
        c_ft = build_ft_z_memory(args.rounds, p)
        c_nft = build_non_ft_z_memory(args.rounds, p)
        c_un = build_unencoded_z_memory(args.rounds, p)

        pL_ft, se_ft, n_ft, _ = logical_error_rate(c_ft, shots, seed=1234)
        pL_nft, se_nft, n_nft, _ = logical_error_rate(c_nft, shots, seed=5678)
        pL_un, se_un, _, _ = logical_error_rate(c_un, shots, seed=9012, use_decoder=False)

        results["ft_logical"].append(pL_ft)
        results["ft_stderr"].append(se_ft)
        results["ft_errors"].append(n_ft)
        results["non_ft_logical"].append(pL_nft)
        results["non_ft_stderr"].append(se_nft)
        results["non_ft_errors"].append(n_nft)
        results["unencoded_logical"].append(pL_un)
        results["unencoded_stderr"].append(se_un)

        dt = time.time() - t0
        print(f"{p:8.5f}  {pL_ft:.5f}±{se_ft:.5f}  {pL_nft:.5f}±{se_nft:.5f}  {pL_un:.5f}±{se_un:.5f}  {dt:5.1f}")

    # Concept-level checks
    results["ft_vs_unencoded_crossover"] = None
    for i, p in enumerate(p_values):
        if results["ft_logical"][i] > results["unencoded_logical"][i]:
            results["ft_vs_unencoded_crossover"] = p
            break

    results["ft_vs_non_ft_ratio_by_p"] = [
        results["non_ft_logical"][i] / max(results["ft_logical"][i], 1e-9)
        for i in range(len(p_values))
    ]

    def fit_slope(xs, ys):
        xs = np.asarray(xs, dtype=float)
        ys = np.asarray(ys, dtype=float)
        mask = (ys > 0) & (xs > 0)
        if mask.sum() < 2:
            return None
        return float(np.polyfit(np.log(xs[mask]), np.log(ys[mask]), 1)[0])

    low_ps = [p for p in p_values if p <= 0.005]
    n_low = len(low_ps)
    if n_low >= 2:
        results["ft_slope_low_p"] = fit_slope(low_ps, results["ft_logical"][:n_low])
        results["non_ft_slope_low_p"] = fit_slope(low_ps, results["non_ft_logical"][:n_low])
        results["unencoded_slope_low_p"] = fit_slope(low_ps, results["unencoded_logical"][:n_low])

    out_path = Path(args.out).expanduser()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nWrote {out_path}")
    print("FT/unencoded crossover p ~", results["ft_vs_unencoded_crossover"])
    if "ft_slope_low_p" in results:
        print(f"Log-log slope low-p:  FT={results['ft_slope_low_p']:.2f}  "
              f"NonFT={results['non_ft_slope_low_p']:.2f}  "
              f"Unenc={results['unencoded_slope_low_p']:.2f}")


if __name__ == "__main__":
    main()
