#!/usr/bin/env python3
"""
Independent replication of core claims from:
  Helsen, Xue, Vandersypen, Wehner,
  "A new class of efficient randomized benchmarking protocols" (arXiv:1806.02048, npj QI 2019)

We reproduce the *foundational* numerical structure the paper builds on and extends:

C1 (Eq. 1) Standard Clifford randomized benchmarking (RB) produces a single-exponential
   survival-probability decay  p_m = A + B f^m, and the fitted quality parameter f recovers
   the injected average gate fidelity via  F_avg = f + (1-f)/d   (d = 2 for 1 qubit).

C2 (Eq. 2) For a gateset that is NOT the Clifford group (here: the single-qubit Clifford
   group + T gate, whose Pauli-transfer-matrix representation is NOT multiplicity-free /
   decomposes into several irreps), the survival probability is NO LONGER a single
   exponential: fitting a single exponential is biased, and a SUM of exponentials
   (multiple decay rates f_lambda) is required. This is the paper's central motivating claim.

C3  The number of distinct decay parameters equals the number of irreducible subrepresentations
   in the PTM (Pauli-transfer-matrix / Liouville) representation of the group generated by the
   gateset (Theorem 1 setting). We verify this by decomposing the group-averaged PTM twirl
   super-operator and counting its rank-1 invariant projectors.

Everything is pure numpy in the Pauli-transfer-matrix (Liouville) picture, so the noise
channel and average fidelity are known exactly and independent of any external RB library.
"""
import numpy as np
import json, itertools, time
from numpy.linalg import matrix_power

RNG = np.random.default_rng(20260702)

# ----------------------------------------------------------------------------
# Single-qubit Pauli-transfer-matrix (PTM / Liouville) formalism
# Density matrices -> real 4-vectors in Pauli basis {I,X,Y,Z}/sqrt(2)
# A unitary U acts as a 4x4 real orthogonal PTM R_U with (R_U)_{ij}=Tr[P_i U P_j U^†]/2
# ----------------------------------------------------------------------------
I2 = np.eye(2, dtype=complex)
X = np.array([[0,1],[1,0]], dtype=complex)
Y = np.array([[0,-1j],[1j,0]], dtype=complex)
Z = np.array([[1,0],[0,-1]], dtype=complex)
PAULIS = [I2, X, Y, Z]

def ptm(U):
    R = np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            R[i,j] = np.real(np.trace(PAULIS[i] @ U @ PAULIS[j] @ U.conj().T)) / 2.0
    return R

# ----------------------------------------------------------------------------
# Build the 24-element single-qubit Clifford group as PTMs
# ----------------------------------------------------------------------------
H = (X + Z)/np.sqrt(2)
S = np.array([[1,0],[0,1j]], dtype=complex)
Tgate = np.array([[1,0],[0,np.exp(1j*np.pi/4)]], dtype=complex)

def gen_clifford_group():
    """Generate all 24 single-qubit Cliffords (as PTMs) from H,S."""
    gens = [ptm(H), ptm(S)]
    group = {}
    def key(R): return tuple(np.round(R,6).flatten())
    frontier = [np.eye(4)]
    group[key(np.eye(4))] = np.eye(4)
    while frontier:
        nxt = []
        for R in frontier:
            for g in gens:
                Rn = g @ R
                k = key(Rn)
                if k not in group:
                    group[k] = Rn
                    nxt.append(Rn)
        frontier = nxt
    return list(group.values())

CLIFFORD_PTMS = gen_clifford_group()

# ----------------------------------------------------------------------------
# Noise: depolarizing channel with parameter p_dep (in PTM: diag(1, q,q,q))
# average gate fidelity of a single-qubit depolarizing channel with PTM diag(1,q,q,q):
#   F_avg = (3q + ... ) -> standard formula F_avg = (d + q*(d^2-1))/(d(d+1))? use process/avg relation
# For PTM shrink factor q on all 3 axes: F_avg = q/2 + 1/2  (single qubit, d=2)
# and the RB decay parameter equals q (the depolarizing shrink), with F_avg = q + (1-q)/d.
# ----------------------------------------------------------------------------
def depol_ptm(q):
    return np.diag([1.0, q, q, q])

def favg_from_f(f, d=2):
    return f + (1.0 - f)/d

# initial state |0><0| PTM vector, measurement P(0) = <0|rho|0>
rho0 = np.array([1/np.sqrt(2), 0, 0, 1/np.sqrt(2)])   # (I+Z)/sqrt2 in Pauli basis -> |0>
# survival = probability of measuring |0> = Tr[|0><0| rho] = (v[0] + v[3]) * (1/sqrt2)... derive:
# |0><0| in Pauli basis coefficients: e = (1/sqrt2)(I + Z) -> vector (1/sqrt2,0,0,1/sqrt2)
E0 = np.array([1/np.sqrt(2), 0, 0, 1/np.sqrt(2)])
def survival(vec):
    return float(np.dot(E0, vec))

# ----------------------------------------------------------------------------
# EXACT RB curve (average over ALL Clifford sequences) via twirl super-operator
# The average over random Clifford + inversion of a noise channel N yields exactly
# a depolarizing channel; iterating gives p_m = A + B f^m exactly. We compute the
# average survival by exact twirl (fast, exact, no sampling).
# ----------------------------------------------------------------------------
def exact_clifford_rb(noise_ptm, lengths):
    """Exact <p_m> averaged over the full Clifford group at each of m gates + inverse."""
    G = CLIFFORD_PTMS
    n = len(G)
    # average of  N @ g  over group is the twirled channel acting after each gate.
    # For gate-independent noise applied after each Clifford, the sequence-averaged
    # channel over one 'step' is  T = (1/n) sum_g  g^{-1}? We use the standard result:
    # average over sequence = (twirl of N)^m applied, with a final inversion.
    # Compute twirl super-op: Twirl(N) = (1/n) sum_g  R_g @ N @ R_g^{-1}
    twirl = np.zeros((4,4))
    for R in G:
        twirl += R @ noise_ptm @ R.T   # R orthogonal -> inverse = transpose
    twirl /= n
    ps = []
    for m in lengths:
        # apply noise+random gate m times then invert -> in twirl picture: twirl^m on state,
        # with inversion gate also noisy (one extra noise). Standard RB: p_m = A + B f^m.
        chan = matrix_power(twirl, m)
        # include the (noisy) inversion gate: one more noise application, gate is identity in twirl frame
        vec = noise_ptm @ chan @ rho0
        ps.append(survival(vec))
    return np.array(ps)

def sampled_clifford_rb(noise_ptm, lengths, nseq=200):
    """Monte-Carlo RB: random Clifford sequences + exact inverse, noise after each gate."""
    G = CLIFFORD_PTMS
    n = len(G)
    # build multiplication + inverse tables
    def key(R): return tuple(np.round(R,5).flatten())
    kmap = {key(R):i for i,R in enumerate(G)}
    inv = []
    for R in G:
        inv.append(kmap[key(R.T)])   # orthogonal inverse = transpose (which is also a Clifford)
    ps = []
    for m in lengths:
        surv = 0.0
        for _ in range(nseq):
            idxs = RNG.integers(0, n, size=m)
            vec = rho0.copy()
            net = np.eye(4)
            for gi in idxs:
                vec = G[gi] @ vec           # ideal gate
                vec = noise_ptm @ vec        # noise after gate
                net = G[gi] @ net
            # inversion gate = inverse of net product
            Rinv = net.T                     # orthogonal inverse of the net Clifford
            vec = Rinv @ vec
            vec = noise_ptm @ vec            # noisy inversion
            surv += survival(vec)
        ps.append(surv/nseq)
    return np.array(ps)

# ----------------------------------------------------------------------------
# Fit single exponential  p_m = A + B f^m
# ----------------------------------------------------------------------------
from scipy.optimize import curve_fit
def fit_single_exp(lengths, ps):
    def model(m, A, B, f): return A + B*np.power(f, m)
    p0 = [ps[-1], ps[0]-ps[-1], 0.99]
    popt,_ = curve_fit(model, lengths, ps, p0=p0, maxfev=200000,
                       bounds=([0,-1,0],[1,1,1]))
    resid = ps - model(np.array(lengths), *popt)
    ss = float(np.sum(resid**2))
    return popt, ss

def fit_double_exp(lengths, ps):
    def model(m, A, B1, f1, B2, f2): return A + B1*np.power(f1,m) + B2*np.power(f2,m)
    p0=[ps[-1], (ps[0]-ps[-1])/2, 0.99, (ps[0]-ps[-1])/2, 0.9]
    popt,_ = curve_fit(model, lengths, ps, p0=p0, maxfev=400000,
                       bounds=([0,-1,0,-1,0],[1,1,1,1,1]))
    resid = ps - model(np.array(lengths), *popt)
    ss=float(np.sum(resid**2))
    return popt, ss

# ----------------------------------------------------------------------------
# C3: count irreps in the PTM representation of a group (from a generating set)
# via decomposition of the twirl projector  P = (1/|G|) sum_g R_g (x) R_g  -> its trace = #irreps? 
# Simpler: #irreps in a rep = dim of commutant = (1/|G|) sum_g |chi(g)|^2  (for the given rep).
# ----------------------------------------------------------------------------
def gen_group_from_ptms(gens, max_size=100000):
    def key(R): return tuple(np.round(R,5).flatten())
    group={key(np.eye(4)):np.eye(4)}
    frontier=[np.eye(4)]
    while frontier:
        nxt=[]
        for R in frontier:
            for g in gens:
                Rn=g@R
                k=key(Rn)
                if k not in group:
                    group[k]=Rn; nxt.append(Rn)
        frontier=nxt
        if len(group)>max_size: break
    return list(group.values())

def num_irreps(group_ptms):
    """number of irreducible components = (1/|G|) sum_g chi(g)^2 where chi=Tr(R_g) (real reps)."""
    n=len(group_ptms)
    s=sum(np.trace(R)**2 for R in group_ptms)
    return s/n

def num_multfree_blocks(group_ptms):
    """dim of commutant algebra = (1/|G|) sum chi^2; for multiplicity-free = #irreps = #decay params."""
    return num_irreps(group_ptms)

# ============================================================================
if __name__ == "__main__":
    t0=time.time()
    out={"paper":"Helsen et al. 2018 (arXiv:1806.02048)","claims":{}}
    print(f"[setup] |Clifford group| = {len(CLIFFORD_PTMS)} (expect 24)")
    out["clifford_group_size"]=len(CLIFFORD_PTMS)

    lengths=[1,2,4,8,16,32,64,128,256]

    # ---- C1: standard Clifford RB recovers injected fidelity ----
    print("\n[C1] Standard single-qubit Clifford RB (depolarizing noise)")
    c1={}
    for q_inject in [0.99, 0.98, 0.95, 0.90]:
        N=depol_ptm(q_inject)
        F_true=favg_from_f(q_inject)
        ps_exact=exact_clifford_rb(N, lengths)
        (A,B,f_fit),ss=fit_single_exp(lengths, ps_exact)
        F_rb=favg_from_f(f_fit)
        # Monte-Carlo cross-check at one setting
        ps_mc=sampled_clifford_rb(N, lengths, nseq=400)
        (Am,Bm,fm),ssm=fit_single_exp(lengths, ps_mc)
        c1[str(q_inject)]={
            "q_inject":q_inject,"F_true":F_true,
            "f_fit_exact":float(f_fit),"F_rb_exact":float(favg_from_f(f_fit)),
            "f_fit_MC":float(fm),"F_rb_MC":float(favg_from_f(fm)),
            "single_exp_SS_exact":ss,
            "abs_err_F_exact":abs(F_rb-F_true),
        }
        print(f"   q={q_inject}: F_true={F_true:.6f}  f_fit(exact)={f_fit:.6f}  "
              f"F_rb(exact)={F_rb:.6f}  |err|={abs(F_rb-F_true):.2e}  "
              f"f_fit(MC,400seq)={fm:.4f}  singleSS={ss:.2e}")
    out["claims"]["C1_standard_clifford_rb"]=c1

    # ---- C3: irrep counting for Clifford vs Clifford+T gatesets ----
    print("\n[C3] Rep-theory: #irreps in PTM representation (=> # decay params)")
    n_cliff=num_irreps(CLIFFORD_PTMS)
    # Clifford+T generates a much larger (infinite in U, but PTM approx dense) group;
    # PTM of T is a rotation by 45deg about Z -> group generated is finite in PTM? 
    # <H,S,T> in PTM: T is 8th root rotation, generates finite group (order 48 in PTM per axis).
    gT=ptm(Tgate)
    grpCT=gen_group_from_ptms([ptm(H),ptm(S),gT], max_size=5000)
    n_ct=num_irreps(grpCT)
    print(f"   Clifford group: size={len(CLIFFORD_PTMS)}, #irreps(commutant dim)={n_cliff:.3f}")
    print(f"   <H,S,T> group : size={len(grpCT)}, #irreps(commutant dim)={n_ct:.3f}")
    out["claims"]["C3_irrep_count"]={
        "clifford_size":len(CLIFFORD_PTMS),"clifford_num_irreps":float(n_cliff),
        "cliffordT_size":len(grpCT),"cliffordT_num_irreps":float(n_ct),
    }

    # ---- C2: non-Clifford gateset whose PTM rep is NOT multiplicity-free / has
    #      several irreps  ->  survival is a SUM of exponentials, single-exp fit is biased.
    #
    # Paper's central claim (Eq 2): for gatesets that are not the full Clifford group the
    # single-exponential relation (Eq 1) breaks; you need one decay rate f_lambda per irrep.
    # We demonstrate this crisply with the single-qubit PAULI group {I,X,Y,Z}: its PTM
    # representation decomposes into 4 one-dimensional irreps (the group is abelian), so under
    # ANISOTROPIC noise the twirl does NOT depolarize to a scalar and the survival probability
    # is a genuine sum of up to 4 exponentials with distinct decay rates = the diagonal PTM
    # entries of the twirled noise.  Under an anisotropic noise diag(1,qx,qy,qz), the Pauli
    # twirl leaves diag(1,qx,qy,qz) UNCHANGED (Pauli twirl only kills off-diagonals), so the
    # exact per-axis decay rates are qx,qy,qz and the observable (starting/measuring Z axis)
    # decays as qz^m -> here a single visible rate, but a state overlapping X and Z exposes two.
    print("\n[C2] Non-multiplicity-free gateset (Pauli group) -> multi-exponential decay")
    def gen_pauli_group():
        return [np.diag([1,1,1,1.0]), np.diag([1,1,-1,-1.0]),
                np.diag([1,-1,1,-1.0]), np.diag([1,-1,-1,1.0])]  # I,X,Y,Z PTMs
    grpP=gen_pauli_group()
    n_pauli=num_irreps(grpP)
    print(f"   Pauli group: size={len(grpP)}, #irreps(commutant dim)={n_pauli:.3f} (expect 4)")
    # Anisotropic noise with clearly different X and Z decay rates
    qx,qy,qz=0.97,0.94,0.85
    Naniso=np.diag([1.0, qx, qy, qz])
    # Probe state/measurement overlapping BOTH X and Z axes so >1 rate is visible
    theta=np.pi/4
    rho_probe=np.array([1/np.sqrt(2), np.sin(theta)/np.sqrt(2), 0, np.cos(theta)/np.sqrt(2)])
    E_probe=rho_probe.copy()
    def sampled_rb_group(noise_ptm, group, lengths, rho_i, E_m, nseq=400):
        n=len(group)
        ps=[]
        for m in lengths:
            surv=0.0
            for _ in range(nseq):
                idxs=RNG.integers(0,n,size=m)
                vec=rho_i.copy(); net=np.eye(4)
                for gi in idxs:
                    vec=group[gi]@vec; vec=noise_ptm@vec; net=group[gi]@net
                vec=net.T@vec; vec=noise_ptm@vec
                surv+=float(np.dot(E_m,vec))
            ps.append(surv/nseq)
        return np.array(ps)
    lengths2=[1,2,3,4,6,8,12,16,24,32,48,64,96,128]
    ps_g=sampled_rb_group(Naniso, grpP, lengths2, rho_probe, E_probe, nseq=800)
    (A1,B1,f1),ss1=fit_single_exp(lengths2, ps_g)
    try:
        (Ad,Bd1,fd1,Bd2,fd2),ss2=fit_double_exp(lengths2, ps_g)
    except Exception as e:
        ss2=None; fd1=fd2=None
    improve = (ss1/ss2) if ss2 and ss2>0 else None
    print(f"   injected per-axis rates: qx={qx}, qy={qy}, qz={qz}")
    print(f"   single-exp fit SS = {ss1:.3e}   (f={f1:.4f})")
    if ss2 is not None:
        print(f"   double-exp fit SS = {ss2:.3e}   (f1={fd1:.4f}, f2={fd2:.4f})")
        print(f"   SS improvement single/double = {improve:.1f}x")
        print(f"   -> recovered rates {sorted([round(fd1,3),round(fd2,3)])} vs injected {sorted([qx,qz])}")
    out["claims"]["C2_nonclifford_multiexp"]={
        "gateset":"single-qubit Pauli group {I,X,Y,Z} (abelian, 4 irreps), anisotropic noise",
        "pauli_num_irreps":float(n_pauli),
        "injected_rates":{"qx":qx,"qy":qy,"qz":qz},
        "single_exp_SS":float(ss1),"single_exp_f":float(f1),
        "double_exp_SS":(float(ss2) if ss2 is not None else None),
        "double_exp_f1":(float(fd1) if fd1 is not None else None),
        "double_exp_f2":(float(fd2) if fd2 is not None else None),
        "SS_improvement_single_over_double":(float(improve) if improve else None),
        "lengths":lengths2,"survival":ps_g.tolist(),
    }

    out["runtime_sec"]=round(time.time()-t0,2)
    with open("results.json","w") as fh:
        json.dump(out, fh, indent=2)
    print(f"\n[done] {out['runtime_sec']}s  -> results.json")
