% nougat interim (pdftotext-derived header) — arXiv:2411.05576
# Observation of Moire Plasmonic Skyrmion Clusters


Skyrmions are topological defects belonging to nontrivial homotopy classes in particle theory. Their
remarkably stable topology has recently been observed in electromagnetic waves. For the evanescent
fields near a surface, this has been realized so far only for elementary optical skyrmions, with a fixed
skyrmion number. Here we report, both in theory and experiment, the concept of moiré plasmonic
skyrmion clusters, where multi-skyrmions are nested to form a large optical skyrmion cluster. By
leveraging twistronics engineering of plasmonic nanostructures, we demonstrate both crystallized
and quasi-crystallized optical skyrmion lattices, revealing an unprecedented degree of topological
control. In a misaligned composite nanostructure, the rapid inverting of optical skyrmion number is
achieved, which is explained by a lattice model. This topological change of moiré plasmonic skyrmion
clusters can serve as a precise beacon of the relative alignment deviation between composite
nanostructures.

