#!/usr/bin/env python3
"""
Dihedral HSP coset-state simulation, faithful to the mechanism generalized by
Ivanyos-Magniez-Santha (quant-ph/0102014) Theorem 13 (§6).

We use the dihedral group D_N = <r, s | r^N = s^2 = 1, s r s = r^{-1}>.
Elements: (a, b) with a in Z_N, b in {0,1}; multiplication:
  (a1, b1) * (a2, b2) = (a1 + (-1)^{b1} a2 mod N, b1 XOR b2).

Hidden subgroup H = {(0,0), (d, 1)}  (an order-2 "reflection" subgroup).
This is the paradigmatic non-Abelian HSP case (Ettinger-Høyer 1999),
which quant-ph/0102014 explicitly generalizes in §6 for groups with an
elementary Abelian normal 2-subgroup and cyclic factor group.

The IMS §6 construction: view D_N via the normal subgroup N = <r> ~ Z_N with
G/N = Z_2 (cyclic). For a coset representative z = s = (0,1), define the
auxiliary function on Z_2 x Z_N:
    F(0, x) = f(x, 0)        # elements of N
    F(1, x) = f((x, 0) * z)  # elements of the non-trivial coset
Then F hides a subgroup of the Abelian group Z_2 x Z_N.

Concretely for our H = {(0,0),(d,1)}:
    (0, x) ~ (0, y)  iff  y = x (nothing to identify in H_intersect_N = {0})
    (0, x) ~ (1, y)  iff  (x, 0) f-equivalent to (y, 0)*s = (y, 1)
                      iff  they lie in the same left coset of H:
                      (x,0) H = {(x,0), (x+d, 1)} so (y,1) in it iff y = x+d
                      i.e. y = x + d (mod N).
So F hides K = <(0, ...), (1, d)>_{Z_2 x Z_N} ~ generated by (1, d).
Abelian HSP on Z_2 x Z_N recovers d immediately.

We SIMULATE the full quantum pipeline (statevector) for small N:
  1. Build coset states |g> |f(g)> and trace out the register.
  2. Compute the paper's headline structural quantity: probability that,
     after Fourier sampling on the abelianized problem Z_2 x Z_N, the
     measurement outcome (chi_b, chi_k) satisfies chi_b + chi_k * d = 0 mod
     (the natural relation for the hidden K).

We reproduce THE quantitative claim implicit in the paper:
  * All measurement outcomes on the abelianized coset-state satisfy the
    lattice equation (b + k*d) mod N == 0 (Abelian HSP correctness);
  * A polynomial number of samples suffices to recover d.
"""

from __future__ import annotations
import json
import math
import time
from dataclasses import dataclass
from collections import Counter
from pathlib import Path

import numpy as np


# --- dihedral group arithmetic -------------------------------------------

def d_mul(g, h, N):
    (a1, b1) = g
    (a2, b2) = h
    return ((a1 + ((-1) ** b1) * a2) % N, (b1 ^ b2))


def d_inv(g, N):
    (a, b) = g
    if b == 0:
        return ((-a) % N, 0)
    # (a, 1)^{-1} = (a, 1) since s r^a s r^a = r^{-a} r^a = 1
    return (a, 1)


def d_elements(N):
    for b in (0, 1):
        for a in range(N):
            yield (a, b)


# --- oracle f hiding H = {(0,0),(d,1)} -----------------------------------

def hide_H(g, d, N):
    """Left cosets of H = {(0,0),(d,1)} in D_N.
    (x, 0) H = {(x, 0), (x + d, 1)}
    So the coset of (x, 0) is labelled by x.
    The coset of (x, 1) = (x - d, 0) * (d, 1) is labelled by (x - d) mod N.
    Choose canonical label = (x - d*b) mod N.
    """
    (x, b) = g
    return ((x - d * b) % N, "coset")  # 2nd field only for readability


# --- abelian HSP pipeline over K = Z_2 x Z_N -----------------------------

def abelian_hsp_state(N: int, d: int) -> np.ndarray:
    """Build the pure state
        1/sqrt(2N) * sum_{b in Z_2, x in Z_N} |b>|x>|F(b, x)>
    then trace out the function register and return the reduced density
    matrix on the first two registers.
    F(0, x) = label of coset of (x, 0)     = x            (in Z_N)
    F(1, x) = label of coset of (x, 0) * s = x            because (x,0)*(0,1)=(x,1),
              which is in coset labelled (x - d) mod N.
    Wait: we choose the auxiliary function per IMS §6:
        F(0, x) = f(x, 0) = x
        F(1, x) = f((x, 0) * z)   where z = s = (0, 1)
                = f((x, 1)) = (x - d) mod N
    So collisions between (0, y) and (1, x) happen iff y = x - d, i.e. x - y = d.
    """
    dim = 2 * N
    # Enumerate distinct function values -> assign an index for the "junk" register
    values = []
    val_index = {}
    for b in (0, 1):
        for x in range(N):
            if b == 0:
                v = ("cos", x)
            else:
                v = ("cos", (x - d) % N)
            if v not in val_index:
                val_index[v] = len(val_index)
            values.append(val_index[v])
    K = len(val_index)

    # Build (2N x K) matrix M[i, k] = 1/sqrt(2N) if F(i)=k else 0.
    M = np.zeros((dim, K), dtype=complex)
    for i, v in enumerate(values):
        M[i, v] = 1.0 / math.sqrt(dim)

    # Reduced density matrix rho on the (b, x) register: rho = M M^dagger.
    rho = M @ M.conj().T
    return rho, K, val_index


def qft_abelian(N: int) -> np.ndarray:
    """QFT on Z_N (unitary)."""
    omega = np.exp(2j * math.pi / N)
    F = np.array([[omega ** (j * k) / math.sqrt(N) for k in range(N)]
                  for j in range(N)], dtype=complex)
    return F


def qft_z2() -> np.ndarray:
    return np.array([[1, 1], [1, -1]], dtype=complex) / math.sqrt(2)


def measurement_distribution(rho: np.ndarray, N: int) -> np.ndarray:
    """Apply QFT_{Z_2} tensor QFT_{Z_N} and read out diagonal (probability
    of outcome (b_hat, k_hat)).
    Register layout: index i = 2 * x + b  ->  b in {0,1}, x in Z_N.
    Actually let's index as i = b * N + x for clarity.
    """
    F = qft_z2()
    G = qft_abelian(N)
    U = np.kron(F, G)   # acts on |b>|x>
    rho_hat = U @ rho @ U.conj().T
    probs = np.real(np.diag(rho_hat))
    probs = np.clip(probs, 0.0, None)
    probs /= probs.sum()
    return probs   # length 2*N, indexed by 2*b_hat*(??)  wait: kron ordering


def outcome_index(bhat: int, khat: int, N: int) -> int:
    """kron(F_2, G_N) -> outer index = bhat, inner index = khat."""
    return bhat * N + khat


def analyze(probs: np.ndarray, d: int, N: int):
    """For each (bhat, khat) with prob > eps, check the paper's relation
    bhat + khat * d == 0 (mod 2N interpretation)."""
    rows = []
    for bhat in (0, 1):
        for khat in range(N):
            p = probs[outcome_index(bhat, khat, N)]
            if p < 1e-12:
                continue
            # Character equation for hidden K = <(1, d)> in Z_2 x Z_N:
            # chi_{(bhat, khat)}(1, d) = (-1)^bhat * omega_N^{khat * d} = 1
            # ie 2 * (khat * d / N) + bhat is an integer, ie
            # (bhat * N + 2 * khat * d) mod (2 * N) == 0
            lhs = (bhat * N + 2 * khat * d) % (2 * N)
            ok = (lhs == 0)
            rows.append({"bhat": bhat, "khat": khat, "prob": float(p),
                         "on_lattice": bool(ok),
                         "lattice_lhs_mod_2N": int(lhs)})
    return rows


def recover_d_from_samples(samples, N):
    """Given samples of (bhat, khat), each satisfies bhat*N + 2*khat*d = 0
    mod 2N.  If bhat=1: khat*d = -N/2 mod N doesn't quite work directly for
    even N; if bhat=0: khat*d = 0 mod N which only tells us khat is a multiple
    of N/gcd(d,N).  Standard: collect samples and solve the modular linear
    system.  Simple version below finds d that maximizes support."""
    scores = Counter()
    for (bhat, khat) in samples:
        for dcand in range(N):
            if (bhat * N + 2 * khat * dcand) % (2 * N) == 0:
                scores[dcand] += 1
    if not scores:
        return None, scores
    (best, _) = scores.most_common(1)[0]
    return best, scores


# ---- driver -------------------------------------------------------------

@dataclass
class Result:
    N: int
    d: int
    rows: list
    all_on_lattice: bool
    n_lattice_outcomes: int
    total_prob_on_lattice: float
    recovered_d: int
    samples_used: int
    match: bool


def run_case(N: int, d: int, num_samples: int = 200, rng: np.random.Generator = None):
    if rng is None:
        rng = np.random.default_rng(20260705)
    rho, K, _ = abelian_hsp_state(N, d)
    probs = measurement_distribution(rho, N)
    rows = analyze(probs, d, N)
    all_on = all(r["on_lattice"] for r in rows)
    tot_on = sum(r["prob"] for r in rows if r["on_lattice"])

    # Draw samples according to probs and recover d
    idx = rng.choice(2 * N, size=num_samples, p=probs)
    samples = [(int(i // N), int(i % N)) for i in idx]
    recovered, scores = recover_d_from_samples(samples, N)

    return Result(
        N=N, d=d, rows=rows,
        all_on_lattice=all_on,
        n_lattice_outcomes=sum(1 for r in rows if r["on_lattice"]),
        total_prob_on_lattice=float(tot_on),
        recovered_d=int(recovered) if recovered is not None else -1,
        samples_used=num_samples,
        match=(recovered == d),
    )


def main():
    out = {"tool_versions": {}, "cases": []}
    import qiskit, qiskit_aer, sys
    out["tool_versions"] = {
        "python": sys.version.split()[0],
        "numpy": np.__version__,
        "qiskit": qiskit.__version__,
        "qiskit_aer": qiskit_aer.__version__,
    }
    t0 = time.time()
    rng = np.random.default_rng(20260705)
    for (N, d) in [(3, 1), (4, 1), (4, 2), (4, 3),
                   (5, 2), (6, 3), (8, 3), (8, 5), (12, 7)]:
        r = run_case(N, d, num_samples=200, rng=rng)
        out["cases"].append({
            "N": r.N, "d": r.d,
            "n_distinct_outcomes": len(r.rows),
            "n_on_lattice": r.n_lattice_outcomes,
            "total_prob_on_lattice": r.total_prob_on_lattice,
            "all_on_lattice": r.all_on_lattice,
            "samples_used": r.samples_used,
            "recovered_d": r.recovered_d,
            "match": r.match,
        })
        print(f"[N={r.N:>2} d={r.d}]  outcomes={len(r.rows):>3}  "
              f"onLatticeMass={r.total_prob_on_lattice:.6f}  "
              f"recovered={r.recovered_d}  match={r.match}")
    out["wall_seconds"] = time.time() - t0
    Path(__file__).with_name("dihedral_hsp_results.json").write_text(
        json.dumps(out, indent=2)
    )
    print("\nsaved: dihedral_hsp_results.json")


if __name__ == "__main__":
    main()
