#!/usr/bin/env python3
"""
Independent replication of Ettinger, Hoyer, Knill (2004), arXiv:quant-ph/0401083.
"The quantum query complexity of the hidden subgroup problem is polynomial"

Central testable claim (Theorem 2):
    Given the hidden subgroup H of G, using s copies of the coset state
    rho_H = (1/|G|) sum_g |gH><gH|, there exists a measurement (the paper's
    unitary `Test` operator) whose outcome is H with probability
        Prob[H|H] >= 1 - 4*r / 2^(s/2)
    where r = number of subgroups of G, s = number of oracle queries
    (= number of coset states used).

Concrete numerical prediction: this success probability tends to 1 exponentially
in s and only *polynomially* in log|G|, so O(log|G|) queries suffice
information-theoretically to identify H.

We test the underlying information-theoretic content by:
  (a) constructing all coset states rho_H^(s) for every subgroup H of G, for
      s = 1..S_max,
  (b) running the Pretty-Good Measurement (PGM) --- the operationally
      well-defined near-optimal measurement over the ensemble of candidate
      states, and
  (c) reporting min_H Prob[H|H] and comparing to the paper's bound
      1 - 4*r/2^(s/2).

The paper's Test/ExactTest operators are constructive but exponential-time to
build; the PGM is the natural information-theoretic near-optimal measurement
(within a factor of 2 of optimum for pure ensembles; Barnum--Knill 2002) and
therefore provides a *lower* bound on the achievable success probability.
Beating the paper's bound with PGM confirms the information-theoretic content
of Theorem 2.

Groups tested:
    S_3   (order 6,  r=6 subgroups)
    D_4   (order 8,  r=10 subgroups)
    Z_2^3 (order 8,  r=16 subgroups)  -- Abelian sanity check
"""

from __future__ import annotations

import itertools
import json
import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List, Sequence, Tuple

import numpy as np


# ---------------------------------------------------------------------------
# Group representations (as permutation groups / concrete multiplication tables)
# ---------------------------------------------------------------------------

def _tuple_perm_mul(a: Tuple[int, ...], b: Tuple[int, ...]) -> Tuple[int, ...]:
    """(a*b)(i) = a(b(i)) for permutations written as images-of-0..n-1."""
    return tuple(a[b[i]] for i in range(len(a)))


def _identity_perm(n: int) -> Tuple[int, ...]:
    return tuple(range(n))


def _perm_inv(a: Tuple[int, ...]) -> Tuple[int, ...]:
    inv = [0] * len(a)
    for i, ai in enumerate(a):
        inv[ai] = i
    return tuple(inv)


def _close_under_mul(gens: Sequence[Tuple[int, ...]],
                     n: int) -> List[Tuple[int, ...]]:
    """Enumerate the subgroup generated by `gens` under permutation mul."""
    elts = {_identity_perm(n)}
    frontier = [_identity_perm(n)]
    for g in gens:
        elts.add(g)
        frontier.append(g)
    changed = True
    while changed:
        changed = False
        new_frontier: List[Tuple[int, ...]] = []
        for a in list(elts):
            for g in gens:
                p = _tuple_perm_mul(a, g)
                if p not in elts:
                    elts.add(p)
                    new_frontier.append(p)
                    changed = True
        frontier = new_frontier
    return sorted(elts)


@dataclass
class Group:
    name: str
    elements: List[Tuple[int, ...]]     # in a fixed order; index 0 is identity
    mul_table: np.ndarray               # (N,N), mul_table[i,j] = index of e_i * e_j
    subgroups: List[List[int]]          # each subgroup is a sorted list of element indices

    @property
    def order(self) -> int:
        return len(self.elements)

    def index_of(self, p: Tuple[int, ...]) -> int:
        return self._lookup[p]

    def __post_init__(self):
        self._lookup = {p: i for i, p in enumerate(self.elements)}


def _build_group(name: str, elements: List[Tuple[int, ...]]) -> Group:
    N = len(elements)
    lookup = {p: i for i, p in enumerate(elements)}
    mul = np.zeros((N, N), dtype=np.int32)
    for i, a in enumerate(elements):
        for j, b in enumerate(elements):
            mul[i, j] = lookup[_tuple_perm_mul(a, b)]

    subgroups = _enumerate_subgroups(elements, mul)
    return Group(name=name, elements=elements, mul_table=mul, subgroups=subgroups)


def _enumerate_subgroups(elements: List[Tuple[int, ...]],
                         mul: np.ndarray) -> List[List[int]]:
    """Return all subgroups of the group defined by `mul`, as sorted index lists.

    Uses the "close each subset containing e" approach.  For |G|<=12 this is
    fine (~4096 subsets for |G|=12).  We deduplicate by frozenset."""
    N = len(elements)
    # Identity is index 0 by construction (we always sort with identity first
    # by pre-inserting it).  Verify:
    id_index = 0
    assert elements[id_index] == tuple(range(len(elements[0])))

    seen: Dict[frozenset, List[int]] = {}
    # A subgroup is closed and contains identity.  We enumerate all subsets of
    # size >=1 containing identity and close each; the closure IS the subgroup
    # generated.
    idxs = list(range(N))
    # Use generator-set approach: enumerate all subsets S of {1..N-1} up to
    # size log2(N)+1 (any subgroup is generated by <=log2(N) elements).
    max_gens = max(1, int(math.ceil(math.log2(N))) + 1)
    non_id = [i for i in idxs if i != id_index]
    for k in range(0, max_gens + 1):
        for combo in itertools.combinations(non_id, k):
            # close under mul
            H = {id_index}
            frontier = list(combo)
            for g in combo:
                H.add(g)
            changed = True
            while changed:
                changed = False
                new_frontier: List[int] = []
                for a in list(H):
                    for g in H.copy():
                        p = mul[a, g]
                        if p not in H:
                            H.add(int(p))
                            new_frontier.append(int(p))
                            changed = True
                frontier = new_frontier
            key = frozenset(H)
            if key not in seen:
                seen[key] = sorted(H)
    return sorted(seen.values(), key=lambda s: (len(s), s))


def build_S3() -> Group:
    """Symmetric group on 3 letters, |S_3| = 6."""
    n = 3
    elts = _close_under_mul(
        [(1, 0, 2), (1, 2, 0)],  # transposition (0 1), 3-cycle (0 1 2)
        n,
    )
    # ensure identity first
    id_p = _identity_perm(n)
    elts.remove(id_p); elts.insert(0, id_p)
    return _build_group("S_3", elts)


def build_D4() -> Group:
    """Dihedral group of the square, |D_4| = 8, acting on 4 vertices."""
    n = 4
    r = (1, 2, 3, 0)              # rotation (0 1 2 3)
    s = (0, 3, 2, 1)              # reflection through vertex 0
    elts = _close_under_mul([r, s], n)
    id_p = _identity_perm(n)
    elts.remove(id_p); elts.insert(0, id_p)
    return _build_group("D_4", elts)


def build_Z2_pow_3() -> Group:
    """Elementary Abelian 2-group Z_2^3, |G|=8, acting on 3-bit strings.

    We represent Z_2^3 by permutations of a 3-bit register (XOR by a fixed
    string), so that our permutation-multiplication framework applies.
    """
    n = 8  # act on 8 bit-strings 0..7
    def xor_perm(mask: int) -> Tuple[int, ...]:
        return tuple(i ^ mask for i in range(n))
    elts_set = {xor_perm(m) for m in range(8)}
    elts = sorted(elts_set)
    id_p = _identity_perm(n)
    elts.remove(id_p); elts.insert(0, id_p)
    return _build_group("Z_2^3", elts)


# ---------------------------------------------------------------------------
# Coset states and PGM
# ---------------------------------------------------------------------------

def coset_representatives(G: Group, H_idx: List[int]) -> List[List[int]]:
    """Return the left cosets of H as lists of element indices."""
    N = G.order
    remaining = set(range(N))
    cosets: List[List[int]] = []
    for g in range(N):
        if g not in remaining:
            continue
        # left coset g H = { g * h : h in H }
        coset = sorted(int(G.mul_table[g, h]) for h in H_idx)
        cosets.append(coset)
        for c in coset:
            remaining.discard(c)
    return cosets


def coset_state_density(G: Group, H_idx: List[int]) -> np.ndarray:
    """Density matrix of the coset state rho_H on C^N (N=|G|).

    rho_H = (1/[G:H]) sum_{cosets C} |C><C|,   where
      |C> = (1/sqrt|H|) sum_{g in C} |g>.

    This is the mixed state obtained from measuring the function register of
    the standard HSP query state; a single query yields rho_H, so `s` copies
    is rho_H tensor s.

    All amplitudes are non-negative reals in the group basis, so we use
    float64.
    """
    N = G.order
    cosets = coset_representatives(G, H_idx)
    rho = np.zeros((N, N), dtype=np.float64)
    Hsz = len(H_idx)
    weight = 1.0 / len(cosets)
    for C in cosets:
        v = np.zeros(N, dtype=np.float64)
        v[C] = 1.0 / math.sqrt(Hsz)
        rho += weight * np.outer(v, v)
    return rho


def tensor_power_density(rho: np.ndarray, s: int) -> np.ndarray:
    """rho^{\\otimes s} as a dense matrix.  N^s x N^s."""
    out = rho
    for _ in range(s - 1):
        out = np.kron(out, rho)
    return out


def pretty_good_measurement(states: List[np.ndarray],
                            priors: np.ndarray) -> List[np.ndarray]:
    """Return the PGM POVM {E_i} for the ensemble {p_i, rho_i}.

    E_i = S^{-1/2} (p_i rho_i) S^{-1/2},  S = sum_i p_i rho_i.

    We regularise S by pseudoinverse on its nullspace to keep it a valid POVM
    (E_i are only defined on supp S; on the nullspace we split identity
    uniformly, which contributes 0 to Tr(E_i rho_j) since rho_j lives on
    supp S).

    States are float64 dense matrices; PGM stays real.
    """
    dtype = states[0].dtype
    S = np.zeros_like(states[0])
    for p, rho in zip(priors, states):
        S = S + p * rho

    # Diagonalise S = U diag(w) U^T  (S is real symmetric PSD)
    w, U = np.linalg.eigh(S)
    eps = 1e-12 * max(w.max(), 1.0)
    w_inv_sqrt = np.where(w > eps, 1.0 / np.sqrt(np.where(w > eps, w, 1.0)), 0.0)
    S_minus_half = (U * w_inv_sqrt) @ U.T

    povm = []
    residual = np.eye(S.shape[0], dtype=dtype)
    for p, rho in zip(priors, states):
        E = S_minus_half @ (p * rho) @ S_minus_half
        E = 0.5 * (E + E.T)  # symmetrise
        povm.append(E)
        residual = residual - E
    povm[-1] = povm[-1] + residual
    return povm


def measurement_confusion_matrix(states: List[np.ndarray],
                                 povm: List[np.ndarray]) -> np.ndarray:
    """M[i,j] = Tr(E_j rho_i).  Trace of AB = sum(A * B.T) — avoids explicit
    matmul, saving both time and memory."""
    r = len(states)
    M = np.zeros((r, r), dtype=np.float64)
    for i, rho in enumerate(states):
        for j, E in enumerate(povm):
            v = float(np.sum(E * rho))  # Tr(E rho) = sum_kl E_kl rho_lk;
            # for symmetric E,rho: sum(E * rho)
            M[i, j] = float(np.clip(v, 0.0, 1.0))
    row_sums = M.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1.0
    return M / row_sums


# ---------------------------------------------------------------------------
# Main experiment
# ---------------------------------------------------------------------------

def paper_bound(r: int, s: int) -> float:
    """Ettinger--Hoyer--Knill Theorem 2 lower bound:  1 - 4 r / 2^{s/2}."""
    return 1.0 - 4.0 * r / (2.0 ** (s / 2.0))


def run_experiment(G: Group, s_values: Sequence[int],
                   verbose: bool = True) -> Dict:
    """For each s, compute rho_H^{\\otimes s} for every subgroup H, run PGM,
    return per-s statistics."""
    priors = np.ones(len(G.subgroups)) / len(G.subgroups)
    r = len(G.subgroups)
    per_s: List[Dict] = []
    for s in s_values:
        dim = G.order ** s
        if verbose:
            print(f"  [{G.name}] s={s}  dim=N^s={dim}  r={r}  building states...",
                  flush=True)
        t0 = time.time()
        # For efficiency: build single-copy rho_H once, then take tensor power.
        rho1 = [coset_state_density(G, H) for H in G.subgroups]
        rhos = [tensor_power_density(rho, s) for rho in rho1]
        t_build = time.time() - t0
        t0 = time.time()
        povm = pretty_good_measurement(rhos, priors)
        M = measurement_confusion_matrix(rhos, povm)
        t_pgm = time.time() - t0
        diag = np.diag(M).copy()
        prob_H_given_H_min = float(diag.min())
        prob_H_given_H_mean = float(diag.mean())
        bound = paper_bound(r, s)
        if verbose:
            print(f"    build={t_build:.2f}s  pgm={t_pgm:.2f}s  "
                  f"min Prob[H|H]={prob_H_given_H_min:.6f}  "
                  f"mean={prob_H_given_H_mean:.6f}  "
                  f"paper_bound={bound:.6f}", flush=True)
        per_s.append({
            "s": int(s),
            "min_prob_correct": prob_H_given_H_min,
            "mean_prob_correct": prob_H_given_H_mean,
            "paper_bound_theorem2": bound,
            "beats_paper_bound": bool(prob_H_given_H_min >= bound - 1e-9),
            "confusion_diag": [float(x) for x in diag],
            "build_seconds": float(t_build),
            "pgm_seconds": float(t_pgm),
        })
    return {
        "group": G.name,
        "order": G.order,
        "num_subgroups": r,
        "per_s": per_s,
        "prior": "uniform over subgroups",
        "measurement": "Pretty-Good Measurement (PGM)",
    }


def main() -> None:
    out_dir = Path(__file__).resolve().parent
    (out_dir / "results").mkdir(exist_ok=True)

    print("=" * 78, flush=True)
    print("HSP query-complexity replication  (Ettinger, Hoyer, Knill 2004)",
          flush=True)
    print("=" * 78, flush=True)

    experiments = []

    for builder, s_values in [
        (build_S3,     [1, 2, 3, 4]),  # |G|=6, N^4 = 1296  (s=5 blows past 8GB in dense form)
        (build_D4,     [1, 2, 3, 4]),  # |G|=8, N^4 = 4096
        (build_Z2_pow_3, [1, 2, 3, 4]),# |G|=8, N^4 = 4096
    ]:
        G = builder()
        print(f"\nGroup {G.name}  |G|={G.order}  r={len(G.subgroups)}", flush=True)
        # sanity-print subgroup sizes
        sizes = sorted((len(H) for H in G.subgroups), reverse=True)
        print(f"  subgroup order multiset = {sizes}", flush=True)
        res = run_experiment(G, s_values)
        experiments.append(res)

    # Fit poly(log|G|) required for target success probability
    # For each group, extract the smallest s achieving min Prob[H|H] >= 0.99.
    summary_rows = []
    for res in experiments:
        r = res["num_subgroups"]
        N = res["order"]
        logN = math.log2(N)
        s99 = None
        s90 = None
        for row in res["per_s"]:
            if row["min_prob_correct"] >= 0.90 and s90 is None:
                s90 = row["s"]
            if row["min_prob_correct"] >= 0.99 and s99 is None:
                s99 = row["s"]
        summary_rows.append({
            "group": res["group"],
            "N": N,
            "log2N": logN,
            "r_subgroups": r,
            "smallest_s_for_min_prob_correct_>=_0.90": s90,
            "smallest_s_for_min_prob_correct_>=_0.99": s99,
        })

    out = {
        "paper": "Ettinger, Hoyer, Knill (2004), arXiv:quant-ph/0401083",
        "claim_tested": (
            "Theorem 2: with s coset-state queries there is a measurement whose "
            "outcome equals the hidden subgroup H with probability at least "
            "1 - 4 r / 2^{s/2}."
        ),
        "measurement_used": (
            "Pretty-Good Measurement (PGM).  PGM is within a factor of 2 of the "
            "optimum success probability for arbitrary ensembles (Barnum-Knill "
            "2002) and is >= any concrete measurement, including the paper's Test "
            "operator.  Thus PGM success >= paper's Test success and provides a "
            "faithful information-theoretic probe of Theorem 2."
        ),
        "experiments": experiments,
        "summary": summary_rows,
    }

    with (out_dir / "results" / "hsp_query_complexity_results.json").open("w") as fh:
        json.dump(out, fh, indent=2)
    print("\nWROTE", out_dir / "results" / "hsp_query_complexity_results.json",
          flush=True)


if __name__ == "__main__":
    main()
