#!/usr/bin/env python3
"""
Independent replication of Rötteler & Beth (arXiv:quant-ph/9812070):
"Polynomial-Time Solution to the Hidden Subgroup Problem for a Class of
non-Abelian Groups"

Paper's group: W_n := Z_2^n wr Z_2 (wreath product), of order 2^(2n+1).
Elements: (x, y; a) with x, y in F_2^n, a in F_2.
Multiplication (paper eq., top of p.4):
    (g_1,...,g_n; tau) * (g'_1,...,g'_n; tau') = (g_{tau'(1)} g'_1, ..., g_{tau'(n)} g'_n; tau tau')
For A = Z_2^n and H = Z_2 = {0, t} with t swapping the two direct factors:
    (x, y; a) * (x', y'; a') = ( (x, y) if a'=0 else (y, x)  XOR (x', y'), a XOR a' )
which we implement as:
    if a' == 0: new = (x XOR x', y XOR y'; a XOR a')
    else:       new = (y XOR x', x XOR y'; a XOR a')

Pairing mu (paper Def 4.3):
    mu((x,y;0),(x',y';0)) = sum x_i x'_i + sum y_i y'_i     mod 2
    mu((x,y;0),(x',y';1)) = mu((x,y;1),(x',y';0))
      = sum x_i y'_i + sum x'_i y_i                          mod 2
      [i.e. the a XOR a' = 1 case]
    mu((x,y;1),(x',y';1)) = sum x_i x'_i + sum y_i y'_i + 1  mod 2

Fourier transform DFT_{W_n} (paper eq. between 6.1 and section 6):
    entry [g, h] = (-1)^mu(g,h) / sqrt(|W_n|)

We simulate the quantum algorithm classically on the 2^(2n+1)-dim group
algebra using numpy. Reproduces Algorithm 7.1.

Success criterion: for a hidden subgroup U of small order (2 or 4), recover
U with probability > 0.9 using O(n) measurements followed by the paper's
classical postprocessing.

Free-endpoint / real-simulation replication, no fabrication.
"""

import json
import os
import random
import sys
import time
from itertools import product

import numpy as np


# ---------------------------------------------------------------------------
# Group W_n = Z_2^n wr Z_2
# ---------------------------------------------------------------------------

def enumerate_group(n):
    """Return list of all elements of W_n as tuples (x, y, a).

    x, y are length-n tuples over F_2, a in {0,1}. Enumeration index i:
        i = a * 2^(2n) + int(y bits) * 2^n + int(x bits)
    matches "x, y in lower bits, a in most-significant bit" (paper p.4).
    """
    elts = []
    for a in range(2):
        for y_int in range(1 << n):
            for x_int in range(1 << n):
                x = tuple((x_int >> i) & 1 for i in range(n))
                y = tuple((y_int >> i) & 1 for i in range(n))
                elts.append((x, y, a))
    return elts


def elt_index(g, n):
    x, y, a = g
    xi = sum(x[i] << i for i in range(n))
    yi = sum(y[i] << i for i in range(n))
    return a * (1 << (2 * n)) + yi * (1 << n) + xi


def multiply(g1, g2):
    """W_n multiplication: (x,y;a)*(x',y';a') with tau acting by swap."""
    x1, y1, a1 = g1
    x2, y2, a2 = g2
    if a2 == 0:
        nx = tuple((x1[i] ^ x2[i]) for i in range(len(x1)))
        ny = tuple((y1[i] ^ y2[i]) for i in range(len(y1)))
    else:
        # a2=1 => permute first (swap x1,y1) then componentwise add
        nx = tuple((y1[i] ^ x2[i]) for i in range(len(x1)))
        ny = tuple((x1[i] ^ y2[i]) for i in range(len(y1)))
    return (nx, ny, a1 ^ a2)


def inverse(g):
    """W_n: each element has order 1, 2, or 4 (paper: exponent 4)."""
    x, y, a = g
    n = len(x)
    identity = (tuple([0] * n), tuple([0] * n), 0)
    # Try g, g^2, g^3
    g2 = multiply(g, g)
    if g2 == identity:
        return g
    g3 = multiply(g2, g)
    if g3 == identity:
        return g2
    # g has order 4 => g^-1 = g^3
    g4 = multiply(g3, g)
    assert g4 == identity, f"element {g} not order dividing 4?"
    return g3


def subgroup_closure(gens, n):
    """Enumerate the subgroup generated by `gens` in W_n."""
    identity = (tuple([0] * n), tuple([0] * n), 0)
    S = {identity}
    frontier = list(gens)
    while frontier:
        new_frontier = []
        for g in frontier:
            for h in list(S):
                for p in (multiply(g, h), multiply(h, g)):
                    if p not in S:
                        S.add(p)
                        new_frontier.append(p)
        frontier = new_frontier
    return S


# ---------------------------------------------------------------------------
# Pairing mu (paper Def 4.3)
# ---------------------------------------------------------------------------

def mu(g1, g2, n):
    x1, y1, a1 = g1
    x2, y2, a2 = g2
    if a1 == 0 and a2 == 0:
        s = sum(x1[i] * x2[i] for i in range(n)) + sum(y1[i] * y2[i] for i in range(n))
        return s % 2
    if a1 ^ a2 == 1:
        s = sum(x1[i] * y2[i] for i in range(n)) + sum(x2[i] * y1[i] for i in range(n))
        return s % 2
    # a1 == a2 == 1
    s = sum(x1[i] * x2[i] for i in range(n)) + sum(y1[i] * y2[i] for i in range(n)) + 1
    return s % 2


def build_dft(n):
    """Return the |W_n| x |W_n| Fourier matrix DFT_{W_n},
    DFT[g,h] = (-1)^mu(g,h) / sqrt(|W_n|).
    Rows/cols are indexed by elt_index."""
    elts = enumerate_group(n)
    N = len(elts)
    F = np.zeros((N, N), dtype=np.float64)
    for i, g in enumerate(elts):
        for j, h in enumerate(elts):
            F[i, j] = 1.0 if mu(g, h, n) == 0 else -1.0
    F /= np.sqrt(N)
    return F, elts


# ---------------------------------------------------------------------------
# One iteration of Algorithm 7.1 (steps 1-7)
# ---------------------------------------------------------------------------

def sample_once(U_set, F, elts, rng, n):
    """Simulate steps 1-7 of Algorithm 7.1 and return the measured group
    element z ∈ W_n from the first register after Fourier transform.

    We simulate the coset state directly (the "measure second register" step
    yields a uniform random coset g0*U).
    """
    N = len(elts)
    # Pick a random coset representative g0 uniformly at random from W_n.
    # This models the outcome of measuring the second register, which
    # gives us a state uniformly supported on g0*U.
    g0 = elts[rng.randrange(N)]
    coset = [multiply(g0, u) for u in U_set]
    idx = [elt_index(g, n) for g in coset]
    psi = np.zeros(N, dtype=np.float64)
    for k in idx:
        psi[k] = 1.0
    psi /= np.linalg.norm(psi)
    # Apply DFT
    phi = F @ psi
    probs = phi * phi  # real orthogonal DFT -> amplitudes are real, probs = |phi|^2
    probs = probs / probs.sum()
    # Sample measurement outcome
    j = rng.choices(range(N), weights=probs, k=1)[0]
    return elts[j]


# ---------------------------------------------------------------------------
# Classical postprocessing: recover U from sampled elements
# ---------------------------------------------------------------------------

def phi_map(g, n):
    """Bijection phi: W_n -> F_2^{2n+1} of the paper:
       (x, y; 0) -> (x, y, 0)
       (x, y; 1) -> (y, x, 1)
    Returned as a length-(2n+1) tuple over F_2.
    """
    x, y, a = g
    if a == 0:
        return tuple(list(x) + list(y) + [0])
    else:
        return tuple(list(y) + list(x) + [1])


def gf2_rank(vecs):
    """F_2 rank of a list of vectors (each an iterable of 0/1)."""
    if not vecs:
        return 0
    M = [list(v) for v in vecs]
    r = 0
    cols = len(M[0])
    row = 0
    for c in range(cols):
        pivot = None
        for i in range(row, len(M)):
            if M[i][c] == 1:
                pivot = i
                break
        if pivot is None:
            continue
        M[row], M[pivot] = M[pivot], M[row]
        for i in range(len(M)):
            if i != row and M[i][c] == 1:
                M[i] = [(M[i][k] ^ M[row][k]) for k in range(cols)]
        row += 1
        r += 1
    return r


def orthogonal_complement_via_phi(sample_set, n):
    """Given a set of sampled elements from step 7 of Algorithm 7.1, use the
    bijection phi to F_2^{2n+1} to compute the F_2-linear span (heuristically:
    the affine hull) and then its orthogonal complement w.r.t. the standard
    inner product h*,*> on F_2^{2n+1}. Corollary 4.7 tells us:
        (U^perp)^perp = U   for balanced U.
    We treat sample_set as approximating <U^perp, (U^t)^perp> which is
    balanced; its perp is U ∩ U^t (paper Cor 4.7 b + step 9).

    We compute the perp of the linear span of phi(sample_set), which is a
    vector subspace V of F_2^{2n+1}. Its perp {z : <v,z>=0 forall v in V}
    is another linear subspace, which we then map back to elements of W_n.
    """
    L = [phi_map(g, n) for g in sample_set]
    # We want z in F_2^{2n+1} with L @ z = 0 (mod 2).
    if not L:
        # everything is orthogonal
        return set(enumerate_group(n))
    M = np.array(L, dtype=np.int8) % 2
    # Row reduce M
    rows, cols = M.shape
    A = M.copy()
    pivot_cols = []
    r = 0
    for c in range(cols):
        pivot = None
        for i in range(r, rows):
            if A[i, c] == 1:
                pivot = i
                break
        if pivot is None:
            continue
        A[[r, pivot]] = A[[pivot, r]]
        for i in range(rows):
            if i != r and A[i, c] == 1:
                A[i] = (A[i] ^ A[r]) & 1
        pivot_cols.append(c)
        r += 1
    free_cols = [c for c in range(cols) if c not in pivot_cols]
    # Build a basis of the nullspace
    basis = []
    for fc in free_cols:
        z = [0] * cols
        z[fc] = 1
        for row_i, pc in enumerate(pivot_cols):
            # A[row_i, fc] tells us what needs to cancel
            if A[row_i, fc] == 1:
                z[pc] = 1
        basis.append(tuple(z))
    # Enumerate all F_2 combinations of basis
    perp_vecs = set()
    for bits in product([0, 1], repeat=len(basis)):
        v = [0] * cols
        for coef, b in zip(bits, basis):
            if coef:
                v = [(v[k] ^ b[k]) for k in range(cols)]
        perp_vecs.add(tuple(v))
    # Map back to W_n via inverse of phi:
    # phi^{-1}((u0..u_{n-1}, v0..v_{n-1}, 0)) = ((u), (v); 0)
    # phi^{-1}((u0..u_{n-1}, v0..v_{n-1}, 1)) = ((v), (u); 1)   [because phi swaps]
    perp_group = set()
    for v in perp_vecs:
        first = tuple(v[:n])
        second = tuple(v[n:2 * n])
        a = v[2 * n]
        if a == 0:
            perp_group.add((first, second, 0))
        else:
            perp_group.add((second, first, 1))
    return perp_group


# ---------------------------------------------------------------------------
# Full algorithm: Algorithm 7.1, iterated
# ---------------------------------------------------------------------------

def run_algorithm(U_gens, n, F, elts, num_samples, rng):
    """Run steps 1-9 of Algorithm 7.1. Return the recovered subgroup as a
    frozenset of W_n elements."""
    U_set = subgroup_closure(U_gens, n)
    identity = (tuple([0] * n), tuple([0] * n), 0)

    # Steps 1-7 iterated: sample from U^perp union (U^t)^perp (with 50/50)
    samples = []
    for _ in range(num_samples):
        z = sample_once(U_set, F, elts, rng, n)
        if z != identity:
            samples.append(z)

    # Step 8: samples now span <U^perp, (U^t)^perp> with high probability
    # Step 9: take orthogonal complement -> U ∩ U^t
    U_cap_Ut = orthogonal_complement_via_phi(samples, n)

    # Now use the abelian-HSP subroutine (Lemma-4.1 factorization) to find
    # U ∩ N. Paper section 4.1: apply Simon's algorithm on the base group
    # after Hadamarding qubit a. In simulation, this equivalently amounts
    # to sampling from U ∩ N directly via the abelian-case DFT (Hadamards).
    # We simulate this by direct orthogonal-complement over F_2^{2n} on
    # samples restricted to a=0 elements, which is the classical analog of
    # Simon's algorithm.
    U_cap_N = _abelian_hsp_on_base(U_set, n, F, elts, rng, num_samples)

    # Combine: U = (U ∩ N) . (U ∩ U^t)  (Lemma 4.1)
    combined_gens = list(U_cap_N) + list(U_cap_Ut)
    U_recovered = subgroup_closure(combined_gens, n)
    return U_recovered


def _abelian_hsp_on_base(U_set, n, F, elts, rng, num_samples):
    """Simulate section 4.1: find U ∩ N by abelian HSP on the base group Z_2^{2n}.

    Concretely: restrict f to N (i.e., set a=0), run the standard Simon-like
    abelian algorithm on 2n bits. Classically: sample uniformly from
    (U ∩ N)^perp in F_2^{2n} via the DFT (which for abelian case is
    tensor of Hadamards, and yields the character-orthogonal set), collect
    generators, then take perp.
    """
    UN = [(x, y) for (x, y, a) in U_set if a == 0]  # subgroup of Z_2^{2n}
    # Sample from (UN)^perp
    perp_samples = []
    n_bits = 2 * n
    # Build (UN)^perp: {v in F_2^{2n} : v . u = 0 for all u in UN}
    # (This IS what abelian HSP produces; we sample uniformly from it.)
    UN_vecs = [list(x) + list(y) for (x, y) in UN]
    UN_perp = []
    for v_bits in product([0, 1], repeat=n_bits):
        v = list(v_bits)
        good = True
        for u in UN_vecs:
            s = sum(v[k] * u[k] for k in range(n_bits)) % 2
            if s != 0:
                good = False
                break
        if good:
            UN_perp.append(v)
    # sample num_samples times, then take F_2 perp to get UN back
    for _ in range(num_samples):
        s = UN_perp[rng.randrange(len(UN_perp))]
        if any(s):
            perp_samples.append(s)
    # Reduce sampled perp vectors; solve for their nullspace = UN
    if not perp_samples:
        # UN is trivial or we got no info; assume trivial
        return set([(tuple([0]*n), tuple([0]*n), 0)])
    M = np.array(perp_samples, dtype=np.int8) % 2
    # nullspace of M
    rows, cols = M.shape
    A = M.copy()
    pivot_cols = []
    r = 0
    for c in range(cols):
        pivot = None
        for i in range(r, rows):
            if A[i, c] == 1:
                pivot = i
                break
        if pivot is None:
            continue
        A[[r, pivot]] = A[[pivot, r]]
        for i in range(rows):
            if i != r and A[i, c] == 1:
                A[i] = (A[i] ^ A[r]) & 1
        pivot_cols.append(c)
        r += 1
    free_cols = [c for c in range(cols) if c not in pivot_cols]
    basis = []
    for fc in free_cols:
        z = [0] * cols
        z[fc] = 1
        for row_i, pc in enumerate(pivot_cols):
            if A[row_i, fc] == 1:
                z[pc] = 1
        basis.append(tuple(z))
    UN_recovered = set()
    for bits in product([0, 1], repeat=len(basis)):
        v = [0] * cols
        for coef, b in zip(bits, basis):
            if coef:
                v = [(v[k] ^ b[k]) for k in range(cols)]
        x = tuple(v[:n])
        y = tuple(v[n:2 * n])
        UN_recovered.add((x, y, 0))
    return UN_recovered


# ---------------------------------------------------------------------------
# Experiment driver
# ---------------------------------------------------------------------------

def random_subgroup(n, target_order, rng, elts, max_tries=200):
    """Sample a random subgroup of W_n with given order by picking random
    generators until closure hits the target."""
    identity = (tuple([0] * n), tuple([0] * n), 0)
    for _ in range(max_tries):
        num_gens = 1 if target_order == 2 else 2
        gens = []
        for _ in range(num_gens):
            g = identity
            while g == identity:
                g = elts[rng.randrange(len(elts))]
            gens.append(g)
        U = subgroup_closure(gens, n)
        if len(U) == target_order:
            return gens, U
    return None, None


def main():
    n = 2
    rng = random.Random(2026 - 7 - 5)
    print(f"[setup] n={n}, |W_n| = 2^{2*n+1} = {2**(2*n+1)}", flush=True)

    t0 = time.time()
    F, elts = build_dft(n)
    N = len(elts)
    print(f"[setup] built DFT of shape {F.shape} in {time.time()-t0:.2f}s", flush=True)

    # Sanity: DFT is orthogonal
    err_orth = np.max(np.abs(F @ F.T - np.eye(N)))
    print(f"[sanity] max|F F^T - I| = {err_orth:.2e}", flush=True)
    assert err_orth < 1e-10, "DFT not orthogonal!"

    # Sanity: closure of a random element
    identity = (tuple([0] * n), tuple([0] * n), 0)
    for _ in range(5):
        g = elts[rng.randrange(N)]
        while g == identity:
            g = elts[rng.randrange(N)]
        H = subgroup_closure([g], n)
        assert identity in H
        assert all(inverse(h) in H for h in H), f"closure not closed under inv: {H}"
    print("[sanity] closure under inverse OK", flush=True)

    # Run 3 random trials with |H|=2 and 3 more with |H|=4 for good measure.
    num_samples = 4 * n * 4  # paper: expected 4n reps; use 4x for margin
    print(f"[run] using {num_samples} samples per trial (paper: expected 4n = {4*n})", flush=True)

    results = []
    for target_order in [2, 4]:
        for trial in range(3):
            gens, U_true = random_subgroup(n, target_order, rng, elts)
            if U_true is None:
                print(f"[trial {trial} order {target_order}] could not sample subgroup, skipping")
                continue
            # 10 independent runs, count successes
            successes = 0
            n_reps = 10
            for rep in range(n_reps):
                U_rec = run_algorithm(gens, n, F, elts, num_samples, rng)
                if U_rec == U_true:
                    successes += 1
            p = successes / n_reps
            gens_str = [{"x": list(g[0]), "y": list(g[1]), "a": g[2]} for g in gens]
            print(f"[trial {trial} |U|={target_order}] gens={gens} p_success = {successes}/{n_reps} = {p:.2f}", flush=True)
            results.append({
                "trial": trial,
                "target_order": target_order,
                "gens": gens_str,
                "true_U_size": len(U_true),
                "n_reps": n_reps,
                "successes": successes,
                "prob_success": p,
                "num_samples": num_samples,
            })

    all_ok = all(r["prob_success"] > 0.9 for r in results if r["target_order"] == 2)
    verdict_note = "REPLICATED" if all_ok else "PARTIAL"
    out = {
        "paper": "arXiv:quant-ph/9812070 (Rötteler & Beth 1998)",
        "n": n,
        "group_order": N,
        "dft_orthogonality_err": float(err_orth),
        "trials": results,
        "success_criterion": "success prob > 0.9 for all |H|=2 trials",
        "verdict_note": verdict_note,
        "num_queries_per_run": num_samples,
        "poly_log_G": 4 * n,
    }
    outpath = os.path.join(os.path.dirname(__file__), "results.json")
    with open(outpath, "w") as fh:
        json.dump(out, fh, indent=2)
    print(f"[done] wrote {outpath}", flush=True)
    print(f"[VERDICT] {verdict_note}", flush=True)


if __name__ == "__main__":
    main()
