#!/usr/bin/env python3
"""
Supplementary experiments for the Rötteler-Beth HSP replication:

  (A) STRESS test at n=2: sweep num_samples from 2 to 40 to see the
      empirical success curve vs the paper's Lemma 6.3 bound
      P(success) >= 1 - 2^{-i/4}, and separately track the abelian and
      non-abelian sample counts.
  (B) Non-abelian generator focus: run trials where U is generated by
      an element with a=1 (a "transversal" element), which requires the
      non-abelian Fourier machinery.
  (C) Scaling: run at n=3 (|W_n| = 128) with 4n = 12 samples per run to
      show the algorithm still recovers H with high probability.

All numpy, real simulation, no fabrication.
"""

import json
import os
import random
import time

import numpy as np

from hsp_wreath import (
    build_dft, enumerate_group, elt_index, subgroup_closure,
    run_algorithm, random_subgroup,
)


def stress_sweep_n2(out):
    n = 2
    rng = random.Random(1234)
    F, elts = build_dft(n)

    # Pick 5 fixed subgroups: 2 with |U|=2 a=0 gen, 2 with |U|=2 a=1 gen, 1 with |U|=4
    fixed = []
    identity = (tuple([0]*n), tuple([0]*n), 0)
    # a=0 gens (in base group)
    fixed.append(("|U|=2, a=0 gen", [((1, 0), (1, 1), 0)]))
    fixed.append(("|U|=2, a=0 gen", [((0, 1), (1, 0), 0)]))
    # a=1 gens (non-abelian: exercises the wreath-specific path)
    fixed.append(("|U|=2, a=1 gen", [((1, 0), (1, 0), 1)]))  # (x,x;1)^2 = (0,0;0)
    fixed.append(("|U|=2, a=1 gen", [((0, 1), (0, 1), 1)]))
    # |U|=4 mixed
    fixed.append(("|U|=4, mixed", [((1, 0), (0, 1), 0), ((1, 1), (1, 1), 1)]))

    sample_counts = [2, 4, 6, 8, 12, 16, 24, 32]
    n_reps = 20
    rows = []
    for label, gens in fixed:
        U_true = subgroup_closure(gens, n)
        for ns in sample_counts:
            successes = 0
            for _ in range(n_reps):
                U_rec = run_algorithm(gens, n, F, elts, ns, rng)
                if U_rec == U_true:
                    successes += 1
            p = successes / n_reps
            rows.append({
                "label": label,
                "gens": [{"x": list(g[0]), "y": list(g[1]), "a": g[2]} for g in gens],
                "true_U_size": len(U_true),
                "num_samples": ns,
                "n_reps": n_reps,
                "successes": successes,
                "prob_success": p,
                "paper_bound_1-2^{-i/4}": 1.0 - 2.0 ** (-ns / 4.0),
            })
            print(f"[stress n=2 {label}] |U|={len(U_true)} samples={ns:2d} p={p:.2f}"
                  f" (paper bound >= {1.0-2.0**(-ns/4.0):.3f})", flush=True)
    out["stress_n2"] = rows


def nonabelian_focus_n2(out):
    """Trials where the hidden subgroup contains a transversal element
    (a=1), so |U ∩ N| < |U| and the non-abelian Fourier is essential."""
    n = 2
    rng = random.Random(9999)
    F, elts = build_dft(n)
    identity = (tuple([0]*n), tuple([0]*n), 0)

    non_abelian_gens = [
        [((1, 0), (1, 0), 1)],
        [((1, 1), (1, 1), 1)],
        [((0, 1), (0, 1), 1)],
        [((0, 0), (0, 0), 1)],  # (0,0;1) itself is order 2
        [((1, 0), (1, 0), 1), ((0, 1), (0, 1), 1)],  # bigger balanced
    ]
    rows = []
    for gens in non_abelian_gens:
        U_true = subgroup_closure(gens, n)
        n_reps = 20
        successes = 0
        for _ in range(n_reps):
            U_rec = run_algorithm(gens, n, F, elts, 4 * n * 4, rng)
            if U_rec == U_true:
                successes += 1
        p = successes / n_reps
        rows.append({
            "gens": [{"x": list(g[0]), "y": list(g[1]), "a": g[2]} for g in gens],
            "true_U_size": len(U_true),
            "n_reps": n_reps,
            "successes": successes,
            "prob_success": p,
        })
        print(f"[non-abelian focus] |U|={len(U_true)} gens={gens} p={p:.2f}", flush=True)
    out["nonabelian_focus_n2"] = rows


def scaling_n3(out):
    """Scaling test at n=3: |W_n| = 128."""
    n = 3
    rng = random.Random(31415)
    print(f"[scaling n=3] building DFT of size {2**(2*n+1)}...", flush=True)
    t0 = time.time()
    F, elts = build_dft(n)
    print(f"[scaling n=3] DFT built in {time.time()-t0:.2f}s", flush=True)

    N = len(elts)
    identity = (tuple([0]*n), tuple([0]*n), 0)

    rows = []
    # Try 4 random |U|=2 and 2 random |U|=4
    plan = [(2, 4), (4, 2)]
    for target_order, count in plan:
        for trial in range(count):
            gens, U_true = random_subgroup(n, target_order, rng, elts)
            if U_true is None:
                continue
            n_reps = 10
            successes = 0
            for _ in range(n_reps):
                U_rec = run_algorithm(gens, n, F, elts, 4 * n * 4, rng)
                if U_rec == U_true:
                    successes += 1
            p = successes / n_reps
            rows.append({
                "trial": trial,
                "target_order": target_order,
                "true_U_size": len(U_true),
                "n_reps": n_reps,
                "successes": successes,
                "prob_success": p,
                "num_samples": 4 * n * 4,
            })
            print(f"[scaling n=3 trial {trial} |U|={target_order}] p={p:.2f}", flush=True)
    out["scaling_n3"] = rows


def main():
    out = {}
    t0 = time.time()
    stress_sweep_n2(out)
    nonabelian_focus_n2(out)
    scaling_n3(out)
    out["wallclock_sec"] = round(time.time() - t0, 2)

    outpath = os.path.join(os.path.dirname(__file__), "stress_results.json")
    with open(outpath, "w") as fh:
        json.dump(out, fh, indent=2)
    print(f"[done] wrote {outpath} in {out['wallclock_sec']}s", flush=True)


if __name__ == "__main__":
    main()
