#!/usr/bin/env python3
"""
Independent replication of Gaitan & Clark (arXiv:1304.5773) —
adiabatic quantum algorithm for the Graph Isomorphism problem.

Implementation follows the "permutation-basis" formulation described in the
QC-200 replication task brief (which is the natural, exponentially-more-compact
model of the same physics used in the paper):

  * Hilbert space is spanned by the n! permutations pi of the symmetric group S_n.
  * Problem Hamiltonian H_P is diagonal in this basis:
        <pi| H_P |pi> = # edges in G1 whose image under pi is NOT an edge of G2
                        + # edges in G2 whose pre-image under pi is NOT an edge of G1
    (this is the standard symmetric edge-mismatch cost;
     it is zero iff pi is a graph isomorphism G1 -> G2.)
  * Driver H_D is the Cayley-graph mixer of S_n generated by adjacent
    transpositions (i, i+1). H_D = D - A where A is the adjacency matrix of that
    Cayley graph and D is the (constant) degree n-1 times identity. Ground state
    of H_D is the uniform superposition over S_n.
  * Time-dependent Hamiltonian: H(s) = (1-s) * H_D + s * H_P, s in [0,1].
  * Adiabatic evolution: Trotterized exp(-i H(s) dt) applied to |psi(0)> =
    uniform superposition.

Reported per (n, instance):
  * ground-state fidelity of the final state |psi(1)> with the true iso subspace
  * minimum spectral gap min_s [E_1(s) - E_0(s)] on a dense s-grid
  * ground-state energy at s=1 (should be 0 for isomorphic pair, > 0 for non-iso)

Runs three instances by default:
  (A) n=4 isomorphic pair
  (B) n=5 isomorphic pair
  (C) n=5 non-isomorphic pair (control)

All Hamiltonians are constructed exactly (no fabrication). Numpy exact
diagonalization is used for the gap sweep since n! <= 120.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import os
import sys
import time
from dataclasses import dataclass, asdict
from typing import Iterable

import numpy as np
import networkx as nx


# ---------------------------------------------------------------------------
# Symmetric-group / permutation utilities
# ---------------------------------------------------------------------------

def enumerate_permutations(n: int) -> list[tuple[int, ...]]:
    """All n! permutations of {0, ..., n-1} in lexicographic order."""
    return list(itertools.permutations(range(n)))


def perm_index(perms: list[tuple[int, ...]]) -> dict[tuple[int, ...], int]:
    return {p: i for i, p in enumerate(perms)}


def compose(a: tuple[int, ...], b: tuple[int, ...]) -> tuple[int, ...]:
    """(a . b)(i) = a[b[i]]  (right action, standard function composition)."""
    return tuple(a[bi] for bi in b)


def apply_transposition(p: tuple[int, ...], i: int, j: int) -> tuple[int, ...]:
    q = list(p)
    q[i], q[j] = q[j], q[i]
    return tuple(q)


# ---------------------------------------------------------------------------
# Cost function and problem Hamiltonian
# ---------------------------------------------------------------------------

def edge_mismatch(G1: nx.Graph, G2: nx.Graph, pi: tuple[int, ...]) -> int:
    """
    Symmetric edge-mismatch count between G1 (relabelled by pi) and G2.

    Interprets pi as the vertex map G1 -> G2, i.e. vertex v of G1 is sent to
    vertex pi(v) of G2. Counts edges of G1 whose image is NOT an edge of G2,
    plus edges of G2 whose preimage is NOT an edge of G1. Zero iff pi is an
    isomorphism.
    """
    e1 = set(map(lambda e: tuple(sorted(e)), G1.edges()))
    e2 = set(map(lambda e: tuple(sorted(e)), G2.edges()))
    forward = {tuple(sorted((pi[u], pi[v]))) for (u, v) in e1}
    # inverse pi^{-1}
    inv = [0] * len(pi)
    for i, v in enumerate(pi):
        inv[v] = i
    backward = {tuple(sorted((inv[u], inv[v]))) for (u, v) in e2}
    mis_fwd = len(forward - e2)
    mis_bwd = len(backward - e1)
    return mis_fwd + mis_bwd


def build_H_P(G1: nx.Graph, G2: nx.Graph,
              perms: list[tuple[int, ...]]) -> np.ndarray:
    diag = np.array([edge_mismatch(G1, G2, p) for p in perms], dtype=np.float64)
    return diag  # kept as 1-D diag; H_P = diag(diag)


# ---------------------------------------------------------------------------
# Driver Hamiltonian (Cayley-graph mixer of S_n, adjacent transpositions)
# ---------------------------------------------------------------------------

def build_H_D(perms: list[tuple[int, ...]], n: int) -> np.ndarray:
    """
    H_D = (n-1)*I - A, where A is the adjacency matrix on S_n whose edges join
    permutations differing by one adjacent transposition (i, i+1). This is a
    graph-Laplacian mixer whose ground state is the uniform superposition.
    """
    idx = perm_index(perms)
    N = len(perms)
    A = np.zeros((N, N), dtype=np.float64)
    for k, p in enumerate(perms):
        for i in range(n - 1):
            q = apply_transposition(p, i, i + 1)
            A[k, idx[q]] = 1.0
    D = (n - 1) * np.eye(N, dtype=np.float64)
    return D - A


# ---------------------------------------------------------------------------
# Adiabatic evolution
# ---------------------------------------------------------------------------

def schedule(s: float) -> tuple[float, float]:
    """Linear schedule H(s) = (1-s)*H_D + s*H_P."""
    return (1.0 - s), s


def total_H(alpha_D: float, alpha_P: float,
            H_D: np.ndarray, H_P_diag: np.ndarray) -> np.ndarray:
    N = H_D.shape[0]
    H = alpha_D * H_D.copy()
    H[np.arange(N), np.arange(N)] += alpha_P * H_P_diag
    return H


def uniform_state(N: int) -> np.ndarray:
    psi = np.ones(N, dtype=np.complex128) / math.sqrt(N)
    return psi


def evolve(psi: np.ndarray, H_D: np.ndarray, H_P_diag: np.ndarray,
           T: float, steps: int) -> np.ndarray:
    """
    Trotterized adiabatic evolution:
      for k = 0..steps-1: s = (k + 0.5)/steps; propagate by exp(-i H(s) dt)
    using dense eigendecomposition at each step (n! <= 120 so this is fine).
    """
    dt = T / steps
    for k in range(steps):
        s = (k + 0.5) / steps
        aD, aP = schedule(s)
        H = total_H(aD, aP, H_D, H_P_diag)
        # exact matrix exponential via Hermitian eig
        w, V = np.linalg.eigh(H)
        phase = np.exp(-1j * w * dt)
        # psi -> V diag(phase) V^dagger psi
        psi = V @ (phase * (V.conj().T @ psi))
    # normalize (small numerical drift)
    psi = psi / np.linalg.norm(psi)
    return psi


def spectrum_along_path(H_D: np.ndarray, H_P_diag: np.ndarray,
                        s_grid: np.ndarray, k: int = 4) -> np.ndarray:
    """Return the lowest k eigenvalues on the s-grid, shape (len(s_grid), k)."""
    N = H_D.shape[0]
    out = np.zeros((len(s_grid), k), dtype=np.float64)
    for i, s in enumerate(s_grid):
        aD, aP = schedule(s)
        H = total_H(aD, aP, H_D, H_P_diag)
        w = np.linalg.eigvalsh(H)
        out[i] = w[:k]
    return out


# ---------------------------------------------------------------------------
# Ground-state / isomorphism analysis
# ---------------------------------------------------------------------------

def iso_permutations(G1: nx.Graph, G2: nx.Graph,
                     perms: list[tuple[int, ...]]) -> list[int]:
    """Indices in perms of all vertex maps that are graph isomorphisms G1->G2."""
    out = []
    for i, p in enumerate(perms):
        if edge_mismatch(G1, G2, p) == 0:
            out.append(i)
    return out


def fidelity_iso(psi: np.ndarray, iso_idx: Iterable[int]) -> float:
    idx = list(iso_idx)
    if not idx:
        return 0.0
    amps = psi[idx]
    return float(np.sum(np.abs(amps) ** 2))


# ---------------------------------------------------------------------------
# Instances
# ---------------------------------------------------------------------------

@dataclass
class Instance:
    label: str
    n: int
    G1_edges: list[tuple[int, int]]
    G2_edges: list[tuple[int, int]]
    expected: str  # "iso" or "noniso"

    def graphs(self) -> tuple[nx.Graph, nx.Graph]:
        G1 = nx.Graph()
        G1.add_nodes_from(range(self.n))
        G1.add_edges_from(self.G1_edges)
        G2 = nx.Graph()
        G2.add_nodes_from(range(self.n))
        G2.add_edges_from(self.G2_edges)
        return G1, G2


def make_instances(rng: np.random.Generator) -> list[Instance]:
    instances: list[Instance] = []

    # ---------- (A) n=4 isomorphic pair ----------
    # G1: 4-cycle 0-1-2-3-0
    G1a_edges = [(0, 1), (1, 2), (2, 3), (0, 3)]
    # relabel by pi = (0->2, 1->0, 2->3, 3->1)
    pi_a = [2, 0, 3, 1]
    G2a_edges = sorted({tuple(sorted((pi_a[u], pi_a[v]))) for (u, v) in G1a_edges})
    instances.append(Instance("n4_iso_C4", 4, G1a_edges, G2a_edges, "iso"))

    # ---------- (B) n=5 isomorphic pair ----------
    # G1: 5-cycle 0-1-2-3-4-0 plus chord 0-2 -> 6 edges
    G1b_edges = [(0, 1), (1, 2), (2, 3), (3, 4), (0, 4), (0, 2)]
    pi_b = [3, 1, 4, 0, 2]
    G2b_edges = sorted({tuple(sorted((pi_b[u], pi_b[v]))) for (u, v) in G1b_edges})
    instances.append(Instance("n5_iso_C5+chord", 5, G1b_edges, G2b_edges, "iso"))

    # ---------- (C) n=5 non-isomorphic control ----------
    # G1c: 5-vertex path 0-1-2-3-4 (degree seq 1,2,2,2,1), 4 edges
    G1c_edges = [(0, 1), (1, 2), (2, 3), (3, 4)]
    # G2c: 5-vertex star K_{1,4} centered at 0 (degree seq 4,1,1,1,1), 4 edges
    G2c_edges = [(0, 1), (0, 2), (0, 3), (0, 4)]
    instances.append(Instance("n5_noniso_path_vs_star", 5, G1c_edges, G2c_edges, "noniso"))

    return instances


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_instance(inst: Instance, T: float, steps: int,
                 gap_points: int = 51) -> dict:
    t0 = time.time()
    G1, G2 = inst.graphs()
    perms = enumerate_permutations(inst.n)
    N = len(perms)

    H_D = build_H_D(perms, inst.n)
    H_P_diag = build_H_P(G1, G2, perms)

    # spectrum sweep
    s_grid = np.linspace(0.0, 1.0, gap_points)
    spec = spectrum_along_path(H_D, H_P_diag, s_grid, k=4)
    gaps = spec[:, 1] - spec[:, 0]
    min_gap_idx = int(np.argmin(gaps))
    min_gap = float(gaps[min_gap_idx])
    s_at_min = float(s_grid[min_gap_idx])
    # Also report the min gap on the INTERIOR of the schedule (s in [0.05, 0.95])
    # because at s=1 the problem Hamiltonian is degenerate whenever there is
    # more than one isomorphism (automorphism group of size > 1 for iso instance,
    # or many equivalent low-energy states for non-iso), which makes the
    # endpoint gap of 0 uninformative about the adiabatic anti-crossing.
    interior_mask = (s_grid >= 0.05) & (s_grid <= 0.95)
    interior_gaps = gaps[interior_mask]
    interior_s = s_grid[interior_mask]
    min_int_idx = int(np.argmin(interior_gaps))
    min_gap_interior = float(interior_gaps[min_int_idx])
    s_at_min_interior = float(interior_s[min_int_idx])

    # ground states of H_P
    iso_idx = iso_permutations(G1, G2, perms)
    hp_min = float(np.min(H_P_diag))

    # adiabatic evolution
    psi0 = uniform_state(N)
    psi_final = evolve(psi0, H_D, H_P_diag, T=T, steps=steps)

    fid = fidelity_iso(psi_final, iso_idx)
    # expected energy of final state under H_P (should be near hp_min if adiabatic)
    E_hp = float(np.sum(H_P_diag * np.abs(psi_final) ** 2))

    # also: dominant support permutations
    prob = np.abs(psi_final) ** 2
    top = np.argsort(prob)[::-1][:5]
    top_list = [{"idx": int(k), "perm": list(perms[k]),
                 "prob": float(prob[k]),
                 "hp": float(H_P_diag[k])} for k in top]

    elapsed = time.time() - t0

    return {
        "label": inst.label,
        "n": inst.n,
        "expected": inst.expected,
        "N_dim": N,
        "G1_edges": inst.G1_edges,
        "G2_edges": inst.G2_edges,
        "num_iso_perms_in_hp0": len(iso_idx),
        "H_P_min": hp_min,
        "H_P_max": float(np.max(H_P_diag)),
        "min_gap": min_gap,
        "s_at_min_gap": s_at_min,
        "min_gap_interior": min_gap_interior,
        "s_at_min_gap_interior": s_at_min_interior,
        "gap_at_s0": float(gaps[0]),
        "gap_at_s1": float(gaps[-1]),
        "T": T,
        "trotter_steps": steps,
        "final_fidelity_iso": fid,
        "final_expected_HP_energy": E_hp,
        "top_final_perms": top_list,
        "iso_perm_indices": iso_idx,
        "spectrum_s": s_grid.tolist(),
        "spectrum_lowk": spec.tolist(),
        "elapsed_sec": elapsed,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--T", type=float, default=50.0,
                        help="total adiabatic time")
    parser.add_argument("--steps", type=int, default=500,
                        help="number of Trotter steps")
    parser.add_argument("--out", type=str,
                        default="report/evidence/results.json")
    args = parser.parse_args()

    rng = np.random.default_rng(20260705)
    instances = make_instances(rng)
    results = []
    for inst in instances:
        print(f"[+] Running {inst.label} (n={inst.n}, N={math.factorial(inst.n)})",
              flush=True)
        res = run_instance(inst, T=args.T, steps=args.steps)
        print(f"    N_dim={res['N_dim']}  min_gap_int={res['min_gap_interior']:.4f}"
              f" @s={res['s_at_min_gap_interior']:.2f}"
              f"  fid_iso={res['final_fidelity_iso']:.4f}"
              f"  E_HP={res['final_expected_HP_energy']:.4f}"
              f"  hp_min={res['H_P_min']}  num_iso={res['num_iso_perms_in_hp0']}",
              flush=True)
        results.append(res)

    outdir = os.path.dirname(args.out) or "."
    os.makedirs(outdir, exist_ok=True)
    with open(args.out, "w") as f:
        json.dump({
            "paper": "arXiv:1304.5773",
            "title": "Graph isomorphism and adiabatic quantum computing",
            "authors": ["Frank Gaitan", "Lane Clark"],
            "T": args.T,
            "trotter_steps": args.steps,
            "results": results,
        }, f, indent=2)
    print(f"[+] Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
